import fs from 'node:fs';import path from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {randomUUID,createHash} from 'node:crypto';
import {startAssetGenerationProvider,createOwnedGenerationMedia} from '../fixtures/asset-generation-provider-fixture.mjs';
const require=createRequire(import.meta.url),{createAssetService}=require('../../src/core/binary/out/modules/generation/service.js'),root=path.resolve('F:/AI/AgentMake/CyberSoftwares/GameCowork/codelyreversebackup/work/tests/asset-auth-'+randomUUID()),media=createOwnedGenerationMedia(root),sha=value=>createHash('sha256').update(value).digest('hex');
for(const authMode of ['none','header'])test('Actual custom REST '+authMode+' authentication yields real image bytes without key-bearing DTOs',async()=>{
 const provider=await startAssetGenerationProvider({root:path.join(root,authMode),media,authMode,apiKeyHeader:'X-Owned-Custom-Key',plans:{OWN_AUTH:{kind:'image',base64:true}}}),service=createAssetService({root:path.join(root,authMode,'runtime/generator'),pollIntervalMs:25,requestTimeoutMs:1000});
 try{
  const {provider:config}=await service.dispatch('generator/saveProvider',{provider:{id:'owned',name:'Own '+authMode,kinds:['image'],baseUrl:provider.baseUrl,model:'owned',authMode,apiKeyHeader:'X-Owned-Custom-Key',...(authMode==='header'?{apiKey:provider.apiKey}:{})}}),{task:start}=await service.dispatch('generator/createTask',{providerId:config.id,kind:'image',prompt:'OWN_AUTH'});
  let task,deadline=Date.now()+5000;for(;;){task=(await service.dispatch('generator/getTask',{taskId:start.id})).task;if(task.status==='completed')break;if(Date.now()>deadline)throw Error('Own auth completion deadline');await new Promise(resolve=>setTimeout(resolve,10));}
  const resource=await service.dispatch('generator/getResource',{taskId:task.id,artifactId:task.artifacts[0].id});assert.equal(sha(Buffer.from(resource.base64,'base64')),media.png.sha256);assert.ok(provider.requests.every(request=>request.authorized));assert.equal(provider.requests.find(request=>request.method==='POST').authHeaderPresent,authMode==='header');assert.equal(JSON.stringify({config,task,resource,requests:provider.requests}).includes(provider.apiKey),false);assert.equal(fs.readFileSync(path.join(root,authMode,'runtime/generator/providers.json'),'utf8').includes(provider.apiKey),false);
 }finally{await service.close();await provider.close();}
});
