// Owned input registration -> actual multipart/JSON HTTP -> actual generated bytes.
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { randomUUID, createHash } from 'node:crypto';
import { deflateSync } from 'node:zlib';
import { createOwnedGenerationMedia } from '../fixtures/asset-generation-provider-fixture.mjs';
const require = createRequire(import.meta.url), { createAssetService } = require('../../src/core/binary/out/modules/generation/service.js');
const root = path.resolve('F:/AI/AgentMake/CyberSoftwares/GameCowork/codelyreversebackup/work/tests/asset-inputs-' + randomUUID()), store = path.join(root, 'runtime'), incoming = path.join(store, 'incoming');
const media = createOwnedGenerationMedia(root), key = 'owned-input-key-' + randomUUID(), sha = bytes => createHash('sha256').update(bytes).digest('hex'), requests = [], sockets = new Set();
let service, peer, baseUrl, registered;
const makeService = () => createAssetService({ root: store, pollIntervalMs: 20, requestTimeoutMs: 3000 });
const query = (kind, data) => service.dispatch('generator/' + kind, data);
function stage(bytes, filename, workspaceKey = 'workspace-a') {
  const inputId = 'i_' + randomUUID(), file = path.join(incoming, inputId + '.bin'); fs.mkdirSync(incoming, { recursive: true }); fs.writeFileSync(file, bytes, { flag: 'wx' });
  return { file, metadata: { inputId, filename, workspaceKey, byteLength: bytes.length, sha256: sha(bytes) } };
}
function register(bytes, filename, workspaceKey) { const staged = stage(bytes, filename, workspaceKey); try { const result = service.registerInput(staged.metadata); assert.equal(fs.existsSync(staged.file), true, 'Native importer still owns cleanup of incoming bytes'); return result.input; } finally { fs.unlinkSync(staged.file); } }
const taskInput = (inputIds, extra = {}) => ({ providerId: 'multipart', kind: 'image', prompt: 'Owned reference generation', workspaceKey: 'workspace-a', inputIds, ...extra });
async function done(taskId) { const deadline = Date.now() + 5000; for (;;) { const { task } = await query('getTask', { taskId }); if (['completed','failed','interrupted'].includes(task.status)) return task; if (Date.now() > deadline) throw Error('Owned reference task deadline'); await new Promise(resolve => setTimeout(resolve, 10)); } }
function provider(id, create) { return { id, name: 'Owned ' + id, baseUrl, kinds: ['image','video','model'], authMode: 'bearer', apiKey: key, model: 'owned-model', adapter: { create, cancel: null } }; }

test.before(async () => {
  peer = http.createServer(async (request, response) => {
    try {
      const chunks = []; for await (const bytes of request) chunks.push(bytes); const bytes = Buffer.concat(chunks), contentType = request.headers['content-type'] || '';
      const record = { route: request.url, contentType, authorized: request.headers.authorization === 'Bearer ' + key, fields: {}, files: [] };
      if (contentType.startsWith('multipart/form-data; boundary=')) {
        const parsed = await new Request('http://127.0.0.1/owned-parser', { method: 'POST', headers: { 'Content-Type': contentType }, body: bytes }).formData();
        for (const [name, value] of parsed.entries()) if (typeof value === 'string') record.fields[name] = value; else { const file = Buffer.from(await value.arrayBuffer()); record.files.push({ name, filename: value.name, mime: value.type, byteLength: file.length, sha256: sha(file) }); }
      } else record.fields = JSON.parse(bytes);
      requests.push(record); const kind = record.fields.kind || 'image', output = media[kind === 'model' ? 'glb' : kind === 'video' ? 'webm' : 'png'];
      response.writeHead(200, { 'Content-Type': 'application/json' }); response.end(JSON.stringify({ status: 'completed', outputs: [{ base64: output.bytes.toString('base64'), mime: output.mimeType }] }));
    } catch (error) { response.writeHead(400, { 'Content-Type': 'application/json' }); response.end(JSON.stringify({ error: error.message })); }
  });
  peer.on('connection', socket => { sockets.add(socket); socket.on('close', () => sockets.delete(socket)); }); await new Promise(resolve => peer.listen(0, '127.0.0.1', resolve)); baseUrl = 'http://127.0.0.1:' + peer.address().port; service = makeService();
  registered = register(media.png.bytes, '参考图.png');
  await query('saveProvider', { provider: provider('multipart', { method: 'POST', path: '/edit', bodyType: 'multipart', bodyTemplate: { kind: '{{kind}}', model: '{{model}}', prompt: '{{prompt}}', options: '{{parameters}}' }, fileFields: [{ name: 'image[]', inputIndex: 'all' }] }) });
  await query('saveProvider', { provider: provider('json-reference', { method: 'POST', path: '/json', bodyTemplate: { kind: '{{kind}}', prompt: '{{prompt}}', image: '{{inputs.0.dataUrl}}', bytes: '{{inputs.0.base64}}', filename: '{{inputs.0.filename}}' } }) });
});
test.after(async () => { await service?.close(); for (const socket of sockets) socket.destroy(); await new Promise(resolve => peer.close(resolve)); });

test('Native registration persists verified immutable input metadata and never publishes filesystem paths', async () => {
  assert.equal(registered.mime, 'image/png'); assert.equal(registered.kind, 'image'); assert.equal(registered.sha256, media.png.sha256);
  assert.equal(registered.filename, '参考图.png'); assert.equal((await query('getInput', { inputId: registered.id, workspaceKey: 'workspace-a' })).input.id, registered.id);
  const list = await query('getInputs', { workspaceKey: 'workspace-a' }); assert.equal(list.inputs.length, 1); assert.equal(JSON.stringify(list).includes(store), false); assert.equal(JSON.stringify(list).includes('_file'), false);
  assert.equal((await query('getInputs', { workspaceKey: 'workspace-b' })).inputs.length, 0);
  await assert.rejects(() => query('getInput', { inputId: registered.id, workspaceKey: 'workspace-b' }), /not found/);
  const pathResult = service.getInputPath(registered.id, 'workspace-a'); assert.equal(sha(fs.readFileSync(pathResult.path)), media.png.sha256); assert.ok(pathResult.path.startsWith(path.join(store, 'inputs') + path.sep));
});

test('Multipart sends actual Unicode-named reference bytes and leaves the HTTP boundary to FormData', async () => {
  const { task: queued } = await query('createTask', taskInput([registered.id], { prompt: 'Owned "prompt"\nline', parameters: { width: 48, transparent: true } })); const task = await done(queued.id); assert.equal(task.status, 'completed', task.error);
  const sent = requests.at(-1); assert.match(sent.contentType, /^multipart\/form-data; boundary=/); assert.equal(sent.authorized, true); assert.equal(sent.fields.prompt.replaceAll('\r\n','\n'), 'Owned "prompt"\nline'); assert.deepEqual(JSON.parse(sent.fields.options), { width: 48, transparent: true });
  assert.deepEqual(sent.files, [{ name: 'image[]', filename: '参考图.png', mime: 'image/png', byteLength: media.png.size, sha256: media.png.sha256 }]);
  assert.equal(task.inputs[0].id, registered.id); assert.equal(task.inputs[0].sha256, media.png.sha256); assert.equal(JSON.stringify(task).includes('_file'), false); assert.equal(JSON.stringify(task).includes('base64'), false);
  await assert.rejects(() => query('deleteInput', { inputId: registered.id, workspaceKey: 'workspace-a' }), /generation history/);
});

test('Typed JSON input variables deliver exact base64/data URLs to the explicitly configured endpoint', async () => {
  const { task: queued } = await query('createTask', taskInput([registered.id], { providerId: 'json-reference' })); const task = await done(queued.id); assert.equal(task.status, 'completed', task.error);
  const sent = requests.at(-1); assert.equal(sent.contentType, 'application/json'); assert.equal(sent.files.length, 0); assert.equal(sent.fields.filename, '参考图.png'); assert.equal(sha(Buffer.from(sent.fields.bytes, 'base64')), media.png.sha256); assert.equal(sent.fields.image, 'data:image/png;base64,' + media.png.bytes.toString('base64'));
});

test('A reference image can drive video and model generation without replacing the actual output kind', async () => {
  for (const [kind, expected] of [['video','video/webm'], ['model','model/gltf-binary']]) {
    const { task: queued } = await query('createTask', taskInput([registered.id], { kind })); const task = await done(queued.id); assert.equal(task.status, 'completed', task.error); assert.equal(task.artifacts[0].mime, expected); assert.equal(requests.at(-1).files[0].sha256, media.png.sha256);
  }
});

test('All existing supported media kinds may be imported and sent in mapped multipart file fields', async () => {
  const references = [register(media.mp4.bytes, 'reference.mp4'), register(media.webm.bytes, 'reference.webm'), register(media.glb.bytes, 'reference.glb')];
  await query('saveProvider', { provider: provider('mapped', { method: 'POST', path: '/mixed', bodyType: 'multipart', bodyTemplate: { kind: '{{kind}}' }, fileFields: [{ name: 'source_video', inputIndex: 0 }, { name: 'alternate_video', inputIndex: 1 }, { name: 'source_model', inputIndex: 2 }] }) });
  const { task: queued } = await query('createTask', taskInput(references.map(input => input.id), { providerId: 'mapped' })); const task = await done(queued.id); assert.equal(task.status, 'completed', task.error);
  assert.deepEqual(requests.at(-1).files.map(file => [file.name,file.mime,file.sha256]), references.map((input,index) => [['source_video','alternate_video','source_model'][index],input.mime,input.sha256]));
});

test('Scope, arbitrary paths, unknown IDs and ignored references fail before any HTTP submission', async () => {
  await query('saveProvider', { provider: provider('ignores-inputs', { method: 'POST', path: '/ignored', bodyTemplate: { prompt: '{{prompt}}' } }) });
  await query('saveProvider', { provider: provider('metadata-only', { method: 'POST', path: '/metadata', bodyTemplate: { filename: '{{inputs.0.filename}}' } }) });
  const before = requests.length;
  for (const change of [{ workspaceKey: 'workspace-b' }, { inputIds: ['i_' + randomUUID()] }, { inputIds: [registered.id,registered.id] }, { inputs: [{ path: 'F:/arbitrary' }] }, { inputPaths: ['F:/arbitrary'] }, { providerId: 'ignores-inputs' }, { providerId: 'metadata-only' }]) await assert.rejects(() => query('createTask', taskInput([registered.id], change)));
  assert.equal(requests.length, before);
});

test('Input references survive restart and participate in scoped idempotency conflicts', async () => {
  const request = taskInput([registered.id], { idempotencyKey: 'owned-input-retry' }), { task: queued } = await query('createTask', request); await done(queued.id); const before = requests.length;
  await service.close(); service = makeService();
  assert.equal((await query('getInput', { inputId: registered.id, workspaceKey: 'workspace-a' })).input.sha256, media.png.sha256);
  const replay = await query('createTask', request); assert.equal(replay.task.id, queued.id); assert.equal(replay.task.inputs[0].id, registered.id); assert.equal(requests.length, before);
  const alternate = register(media.png.bytes, 'alternate.png'); await assert.rejects(() => query('createTask', { ...request, inputIds: [alternate.id] }), /Idempotency key conflicts/);
  assert.equal((await query('deleteInput', { inputId: alternate.id, workspaceKey: 'workspace-a' })).deleted, true); await assert.rejects(() => query('getInput', { inputId: alternate.id, workspaceKey: 'workspace-a' }), /not found/);
});

test('Native checksum/size/path/link mismatches and damaged image bytes never register', async () => {
  const before = (await query('getInputs', { workspaceKey: 'workspace-a' })).inputs.length;
  for (const change of [{ sha256: '0'.repeat(64) }, { byteLength: media.png.size + 1 }, { path: 'F:/arbitrary' }]) { const staged = stage(media.png.bytes, 'owned.png'); try { assert.throws(() => service.registerInput({ ...staged.metadata, ...change })); } finally { fs.unlinkSync(staged.file); } }
  const damaged = Buffer.from(media.png.bytes); damaged[41] ^= 1; const bad = stage(damaged, 'damaged.png'); try { assert.throws(() => service.registerInput(bad.metadata), /PNG checksum/); } finally { fs.unlinkSync(bad.file); }
  const linked = stage(media.png.bytes, 'linked.png'), alias = path.join(root, 'own-hardlink.png'); fs.linkSync(linked.file, alias); try { assert.throws(() => service.registerInput(linked.metadata), /Linked/); } finally { fs.unlinkSync(alias); fs.unlinkSync(linked.file); }
  assert.equal((await query('getInputs', { workspaceKey: 'workspace-a' })).inputs.length, before);
});

test('Reference bytes are rechecked before submission and cannot be swapped after registration', async () => {
  const owned = register(media.png.bytes, 'tamper.png'), file = service.getInputPath(owned.id, 'workspace-a').path, before = requests.length; fs.appendFileSync(file, 'tamper');
  try { await assert.rejects(() => query('createTask', taskInput([owned.id])), /integrity/); assert.equal(requests.length, before); } finally { fs.writeFileSync(file, media.png.bytes); }
  await query('deleteInput', { inputId: owned.id, workspaceKey: 'workspace-a' });
});

test('A real Windows FILE_SHARE_READ preview lock leaves failed deletion fully retryable', { skip: process.platform !== 'win32' }, async () => {
  const input = register(media.png.bytes, 'shared-read.png'), file = service.getInputPath(input.id, 'workspace-a').path, metadata = path.join(store, 'inputs.json'), before = fs.readFileSync(metadata);
  const script = "$reader=[System.IO.File]::Open('" + file.replaceAll("'", "''") + "',[System.IO.FileMode]::Open,[System.IO.FileAccess]::Read,[System.IO.FileShare]::Read); [Console]::Out.WriteLine('owned-reader-ready'); [Console]::In.ReadLine() | Out-Null; $reader.Dispose()";
  const child = spawn('powershell', ['-NoProfile', '-NonInteractive', '-EncodedCommand', Buffer.from(script, 'utf16le').toString('base64')], { windowsHide: true, stdio: ['pipe','pipe','pipe'] });
  const exited = new Promise(resolve => child.once('exit', resolve)); let output = '', stderr = '';
  child.stderr.on('data', bytes => { stderr += bytes; });
  try {
    await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(Error('Owned shared reader deadline: ' + stderr)), 10000); child.stdout.on('data', bytes => { output += bytes; if (output.includes('owned-reader-ready')) { clearTimeout(timer); resolve(); } }); child.once('error', error => { clearTimeout(timer); reject(error); }); });
    await assert.rejects(() => query('deleteInput', { inputId: input.id, workspaceKey: 'workspace-a' }), /EBUSY|EPERM|locked|permission/);
    assert.deepEqual(fs.readFileSync(metadata), before); assert.equal((await query('getInput', { inputId: input.id, workspaceKey: 'workspace-a' })).input.sha256, input.sha256);
    assert.deepEqual(fs.readFileSync(file), media.png.bytes); assert.equal(fs.readdirSync(path.join(store,'inputs')).some(name => name.startsWith('.delete-' + input.id)), false);
  } finally { child.stdin.end('\n'); assert.equal(await exited, 0); }
  assert.equal((await query('deleteInput', { inputId: input.id, workspaceKey: 'workspace-a' })).deleted, true); assert.equal(fs.existsSync(file), false); assert.equal(Object.hasOwn(JSON.parse(fs.readFileSync(metadata)), input.id), false);
});

test('Metadata persistence failure rolls a staged deletion back to its usable original file', async () => {
  const input = register(media.png.bytes, 'rollback-delete.png'), file = service.getInputPath(input.id, 'workspace-a').path, metadata = path.join(store, 'inputs.json'), alias = path.join(root, 'inputs-delete-rollback-hardlink.json');
  const before = fs.readFileSync(metadata); fs.linkSync(metadata, alias);
  try {
    await assert.rejects(() => query('deleteInput', { inputId: input.id, workspaceKey: 'workspace-a' }), /Linked/);
    assert.deepEqual(fs.readFileSync(metadata), before); assert.deepEqual(fs.readFileSync(file), media.png.bytes); assert.equal((await query('getInput', { inputId: input.id, workspaceKey: 'workspace-a' })).input.sha256, input.sha256);
    assert.equal(fs.readdirSync(path.join(store,'inputs')).some(name => name.startsWith('.delete-' + input.id)), false);
  } finally { fs.unlinkSync(alias); }
  await service.close(); service = makeService(); assert.equal((await query('getInput', { inputId: input.id, workspaceKey: 'workspace-a' })).input.sha256, input.sha256);
  assert.equal((await query('deleteInput', { inputId: input.id, workspaceKey: 'workspace-a' })).deleted, true); assert.equal(fs.existsSync(file), false);
});

test('Cleanup failure after metadata commit restores both the input registry and its original file', async () => {
  const input = register(media.png.bytes, 'cleanup-rollback.png'), file = service.getInputPath(input.id, 'workspace-a').path, metadata = path.join(store, 'inputs.json'), before = fs.readFileSync(metadata), unlink = fs.unlinkSync;
  let injected = false;
  fs.unlinkSync = target => {
    if (path.basename(String(target)).startsWith('.delete-' + input.id)) {
      injected = true; assert.equal(Object.hasOwn(JSON.parse(fs.readFileSync(metadata)), input.id), false, 'The fault occurs after the registry commit');
      const error = new Error('Owned injected cleanup EBUSY'); error.code = 'EBUSY'; throw error;
    }
    return unlink(target);
  };
  try { await assert.rejects(() => query('deleteInput', { inputId: input.id, workspaceKey: 'workspace-a' }), /Owned injected cleanup EBUSY/); }
  finally { fs.unlinkSync = unlink; }
  assert.equal(injected, true); assert.deepEqual(fs.readFileSync(metadata), before); assert.deepEqual(fs.readFileSync(file), media.png.bytes);
  assert.equal((await query('getInput', { inputId: input.id, workspaceKey: 'workspace-a' })).input.sha256, input.sha256);
  assert.equal((await query('deleteInput', { inputId: input.id, workspaceKey: 'workspace-a' })).deleted, true);
});

test('Invalid multipart mappings, unsupported types and unsafe credential Content-Type are rejected on save', async () => {
  const changes = [{ bodyType: 'unsupported' }, { bodyType: 'multipart', method: 'GET' }, { bodyType: 'multipart', bodyTemplate: 'scalar' }, { bodyType: 'multipart', fileFields: [{ name: 'unsafe\r\nname', inputIndex: 0 }] }, { bodyType: 'multipart', fileFields: [{ name: 'image', inputIndex: 8 }] }, { bodyType: 'json', fileFields: [{ name: 'image', inputIndex: 0 }] }, { bodyTemplate: { image: '{{inputs.0.path}}' } }];
  for (const change of changes) await assert.rejects(() => query('saveProvider', { provider: provider('invalid', { method: 'POST', path: '/invalid', ...change }) }));
  await assert.rejects(() => query('saveProvider', { provider: { ...provider('invalid-header', { method: 'POST', path: '/invalid', bodyType: 'multipart' }), authMode: 'header', apiKeyHeader: 'Content-Type' } }), /Unsafe/);
});

test('More than eight references or unbound multipart slots are rejected before transport', async () => {
  const before = requests.length;
  await assert.rejects(() => query('createTask', taskInput(Array.from({ length: 9 }, () => 'i_' + randomUUID()))), /at most eight/);
  await query('saveProvider', { provider: provider('missing-slot', { method: 'POST', path: '/missing-slot', bodyType: 'multipart', fileFields: [{ name: 'mask', inputIndex: 1 }] }) });
  await assert.rejects(() => query('createTask', taskInput([registered.id], { providerId: 'missing-slot' })), /unavailable input index/);
  assert.equal(requests.length, before);
});

test('Five real 13 MiB inputs exceed the combined limit, and duplicate multipart body bytes have a separate request budget', async () => {
  const table = new Uint32Array(256); for (let i = 0; i < 256; i++) { let value = i; for (let bit = 0; bit < 8; bit++) value = value >>> 1 ^ (value & 1 ? 0xedb88320 : 0); table[i] = value; }
  const chunk = (name, data) => { const result = Buffer.alloc(data.length + 12); result.writeUInt32BE(data.length); result.write(name, 4); data.copy(result, 8); let checksum = 0xffffffff; for (let i = 4; i < result.length - 4; i++) checksum = checksum >>> 8 ^ table[(checksum ^ result[i]) & 255]; result.writeUInt32BE((checksum ^ 0xffffffff) >>> 0, result.length - 4); return result; };
  const width = 2048, height = 1700, header = Buffer.alloc(13); header.writeUInt32BE(width); header.writeUInt32BE(height,4); header[8] = 8; header[9] = 6;
  const pixels = Buffer.alloc((width * 4 + 1) * height), bytes = Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels,{level:0})),chunk('IEND',Buffer.alloc(0))]); assert.ok(bytes.length * 5 > 64 * 1024 * 1024);
  const inputs = Array.from({ length: 5 }, (_, index) => register(bytes, 'owned-large-' + index + '.png')), before = requests.length;
  await assert.rejects(() => query('createTask', taskInput(inputs.map(input => input.id))), /combined 64 MiB/); assert.equal(requests.length, before);
  await query('saveProvider', { provider: provider('duplicate-files', { method: 'POST', path: '/duplicated-input', bodyType: 'multipart', fileFields: Array.from({ length: 8 }, (_, index) => ({ name: 'image_' + index, inputIndex: 0 })) }) });
  const { task: queued } = await query('createTask', taskInput([inputs[0].id], { providerId: 'duplicate-files' })), task = await done(queued.id);
  assert.equal(task.status, 'failed'); assert.equal(task.mayContinue, false); assert.match(task.error, /multipart body exceeds 96 MiB/); assert.equal(requests.length, before, 'Local body preparation failures must not submit or report an unknown remote outcome');
  await query('saveProvider', { provider: provider('duplicate-json', { method: 'POST', path: '/duplicated-json', bodyTemplate: { a:'{{inputs.0.base64}}', b:'{{inputs.0.base64}}', c:'{{inputs.0.base64}}', d:'{{inputs.0.base64}}', e:'{{inputs.0.base64}}', f:'{{inputs.0.base64}}' } }) });
  const jsonQueued = await query('createTask', taskInput([inputs[1].id], { providerId: 'duplicate-json' })), jsonTask = await done(jsonQueued.task.id);
  assert.equal(jsonTask.status, 'failed'); assert.equal(jsonTask.mayContinue, false); assert.match(jsonTask.error, /request body exceeds/); assert.equal(requests.length, before);
});
