const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {projectModelMenu}=require('../../src/core/binary/out/modules/account/official-model-menu.js');
const {createOfficialLlmService,wireApi}=require('../../src/core/binary/out/modules/account/official-llm.js');
const row=(name,model,rate)=>({name,model,provider:'openai',roles:['chat','apply','edit'],rate,capabilities:['tool_use'],extras:{thinkingEfforts:{default:'max',options:['high','max']},maxContextLengths:{default:128000,options:[128000,256000]},model:{default:model,options:[model]}},defaultCompletionOptions:{contextLength:128000,maxTokens:32000}});
const config={models:[row('Core (GLM-5.3)','fixture-core',.25),row('Basic','fixture-basic',.1),row('GLM-5.3-FLASH','fixture-flash',.1),row('DeepSeek-V4.1-Fixture','fixture-deepseek',.1),row('KIMI-K3','fixture-kimi',1)]};
test('Native configuration retains original order/fields, appends gray Frontier and drops credential/endpoint/rule material',()=>{
  const input=structuredClone(config);Object.assign(input.models[0],{apiKey:'owned-secret',apiBase:'https://private.invalid',requestOptions:{headers:{Authorization:'owned-secret'}},class_name:'OriginalFixtureClass',description:'Native description'});input.models[0].extras.envVars={TOKEN:'owned-secret'};
  const result=projectModelMenu(input,{secrets:['owned-secret']});assert.deepEqual(result.map(row=>row.name),[...config.models.map(row=>row.name),'Frontier']);assert.deepEqual(result.slice(0,5).map(row=>row.rate),[.25,.1,.1,.1,1]);assert.equal(result[0].class_name,'OriginalFixtureClass');assert.deepEqual(result[0].defaultCompletionOptions,{contextLength:128000,maxTokens:32000});assert.deepEqual(result[0].extras,config.models[0].extras);assert.equal(result.at(-1).disabled,true);assert.equal(result.at(-1).placeholder,true);assert.doesNotMatch(JSON.stringify(result),/owned-secret|private\.invalid|requestOptions|envVars/);
  assert.deepEqual(projectModelMenu({models:[]}),[]);assert.throws(()=>projectModelMenu({models:[{...config.models[0],disabled:'true'}]}),/disabled must be boolean/);
  assert.equal(projectModelMenu({models:[row('Frontier','Frontier',1)]})[0].disabled,true);
});
test('Keyless canonical metadata is independent of Pro labels and all disabled/empty/anonymous menus remain non-executable',async t=>{
  let alive=true,keyCalls=0,menuCalls=0,data=config,binding={accountId:'fixture-account',teamId:'fixture-team',generationKey:'fixture-epoch'};
  const surface={getModelMenuConfig:async()=>{menuCalls++;return{binding:{...binding},models:projectModelMenu(data)};},isModelMenuBindingCurrent:expected=>alive&&expected.generationKey===binding.generationKey,inferenceBinding:async()=>({...binding}),isInferenceBindingCurrent:expected=>alive&&expected.generationKey===binding.generationKey,getCliInferenceCredential:async()=>{keyCalls++;return{cliApiKey:'owned-secret'};},onInferenceInvalidated:()=>()=>{}};
  const service=createOfficialLlmService({surface:()=>alive?surface:null,currentWorkspace:()=>path.resolve('tests/fixtures'),fetch:()=>assert.fail('No inference or raw alias directory request'),clientInfo:async()=>({ideType:'gamecowork-desktop',extensionVersion:'2.1.3-canary.2'})});t.after(()=>service.close());
  assert.deepEqual(await service.refreshMenu(),{ready:true,source:'original-config-v3',modelCount:5});assert.equal(keyCalls,0);assert.equal(menuCalls,1);const native=service.selectedModel(service.models()[0].id);assert.equal(native.customedModel,false);assert.equal(native.rate,.25);assert.equal(native.contextLength,128000);assert.equal(native.capabilities.tools,true);assert.deepEqual(native.extras.thinkingEfforts,config.models[0].extras.thinkingEfforts);assert.equal(service.lookup('Frontier'),null);await assert.rejects(service.sessionEnvironment('blocked',path.resolve('tests/fixtures'),'Frontier',()=>true),/官方模型/);assert.equal(keyCalls,0);
  data={models:[{...row('Basic','fixture-basic',.1),disabled:true}]};await service.refreshMenu();assert.equal(service.status().modelCount,0);assert.equal(service.profiles()[0].disabled,true);assert.equal(service.selectedModel('Basic'),null);assert.equal(keyCalls,0);
  data={models:[]};assert.equal((await service.refreshMenu()).ready,true);assert.deepEqual(service.profiles(),[]);alive=false;assert.deepEqual(await service.refreshMenu(),{ready:false,source:'original-config-v3',modelCount:0,unavailableReason:'requires_login'});assert.equal(keyCalls,0);
});
test('Original Core wire derivation uses the real model and declared extras, never an encoded menu identity',()=>{
  assert.equal(wireApi({id:'codely-official:ZXhhbXBsZQ',model:'messages/fixture-claude'}),'messages');assert.equal(wireApi({id:'codely-official:ZXhhbXBsZQ',model:'gpt-fixture'}),'responses');assert.equal(wireApi({model:'gpt-fixture',extras:{wireApi:{default:'chat',options:['chat']}}}),'chat');
});
for(const file of ['index.js','index.beautified.js'])test(file+': original native construction precedes custom collision handling and preserves fields without custom fallback',async()=>{
  const source=fs.readFileSync(path.join(__dirname,'../../src/core/binary/out',file),'utf8'),start=source.indexOf('async function Nua('),end=source.indexOf('var Xua',start);assert(start>=0&&end>start);
  const models=projectModelMenu(config),profiles=models.map(row=>({...row,name:row.officialModelId,displayName:row.name}));profiles.push({name:'owned-custom',model:'custom-api',displayName:'Core (GLM-5.3)',providerName:'Owned Provider',roles:['model']});
  const state={modelsByRole:{chat:[],summarize:[],apply:[],edit:[]}},context=vm.createContext({PHi:()=>['chat','summarize','apply','edit'],qHi:()=>undefined,npe:async({model})=>[{...model,title:model.name,extras:model.extras,capabilities:model.capabilities}],});vm.runInContext(source.slice(start,end)+';this.run=Nua;',context);await context.run({gamecoworkModelProfilesList:{profiles},config:state,uniqueId:'owned',errors:[],ide:{}});
  assert.equal(state.modelsByRole.chat.length,7);assert.equal(state.modelsByRole.chat[0].title,'Core (GLM-5.3)');assert.equal(state.modelsByRole.chat[0].customedModel,false);assert.equal(state.modelsByRole.chat[0].rate,.25);assert.equal(state.modelsByRole.chat[5].disabled,true);assert.equal(state.modelsByRole.chat[6].title,'Core (GLM-5.3) (Owned Provider)');assert.equal(state.modelsByRole.chat[6].customedModel,true);assert.equal(state.modelsByRole.chat[0].extras.officialModelId,models[0].officialModelId);assert.equal(state.modelsByRole.chat[0].defaultCompletionOptions.maxTokens,32000);assert.equal(state.modelsByRole.chat[0].capabilities.includes('tool_use'),true);
  const fpaStart=source.indexOf('async function fpa('),fpaEnd=source.indexOf('S0();',fpaStart);const loader=vm.createContext({gcuLocalProfiles:async()=>({profiles:[{name:'custom'}]}),require:()=>({profiles:async()=>[{name:'native'}]})});vm.runInContext(source.slice(fpaStart,fpaEnd)+';this.run=fpa;',loader);assert.deepEqual(Array.from((await loader.run({})).profiles,row=>row.name),['native','custom']);
  assert.ok(/h\s*=\s*p\.extras\?\.officialModelId\s*\?\s*void 0\s*:\s*b/.test(source),'An official native title cannot adopt a colliding local Provider');
});
test('Pure rate/logo refresh preserves an active model ticket; disabling that model revokes it',async t=>{
  let data={models:[row('Core (GLM-5.3)','fixture-core',.25)]},keys=0;const binding={accountId:'fixture-a',teamId:'fixture-t',generationKey:'fixture-generation'};
  const surface={getModelMenuConfig:async()=>({binding,models:projectModelMenu(data)}),isModelMenuBindingCurrent:()=>true,inferenceBinding:async()=>binding,isInferenceBindingCurrent:()=>true,getCliInferenceCredential:async()=>{keys++;return{cliApiKey:'owned-private-key'};},onInferenceInvalidated:()=>()=>{}};
  const service=createOfficialLlmService({surface:()=>surface,currentWorkspace:()=>path.resolve('tests/fixtures'),fetch:()=>assert.fail('Ticket probe never performs inference')});t.after(()=>service.close());await service.refreshMenu();const model=service.models()[0],env=await service.sessionEnvironment('owned-session',path.resolve('tests/fixtures'),model.id,()=>true);
  const probe=()=>fetch(env.GAMECOWORK_OFFICIAL_LOOPBACK+'/models',{headers:{Authorization:'Bearer '+env.GAMECOWORK_OFFICIAL_CAPABILITY}});
  assert.equal((await probe()).status,200);data.models[0].rate=.1;data.models[0].logoUrl='https://fixture.invalid/icon.png';await service.refreshMenu();assert.equal((await probe()).status,200);assert.equal(keys,1);
  data.models[0].disabled=true;await service.refreshMenu();assert.equal((await probe()).status,401);assert.equal(service.selectedModel('Core (GLM-5.3)'),null);
});
test('An old raw scoped ID migrates only to a unique current allowed chat descriptor',async t=>{
  let data={models:[row('Core (GLM-5.3)','owned-model',.25)]};const binding={accountId:'a',teamId:'t',generationKey:'g'},surface={getModelMenuConfig:async()=>({binding,models:projectModelMenu(data)}),isModelMenuBindingCurrent:()=>true,onInferenceInvalidated:()=>()=>{}};
  const service=createOfficialLlmService({surface:()=>surface,currentWorkspace:()=>'.',fetch:()=>assert.fail('Migration cannot request an inference credential')});t.after(()=>service.close());const legacy='codely-official:'+Buffer.from('owned-model').toString('base64url');await service.refreshMenu();assert.equal(service.selectedModel(legacy).title,'Core (GLM-5.3)');assert.equal(service.selectedModel(legacy).customedModel,false);
  data.models.push(row('Basic','owned-model',.1));await service.refreshMenu();assert.equal(service.selectedModel(legacy),null,'Ambiguous legacy identity cannot silently select a different billed preset');data.models=[{...data.models[0],disabled:true}];await service.refreshMenu();assert.equal(service.selectedModel(legacy),null);data.models=[{...data.models[0],disabled:false,roles:['embed']}];await service.refreshMenu();assert.equal(service.selectedModel(legacy),null);
});
