const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{randomUUID}=require('node:crypto');
const repo=path.resolve(__dirname,'../..'),run=path.resolve(repo,'../../temp/GameCowork','insight-max-turns-contract-'+randomUUID());fs.mkdirSync(run,{recursive:true});
for(const file of['index.js','index.beautified.js']){
 const source=fs.readFileSync(path.join(repo,'src/core/binary/out',file),'utf8');
 const start=source.indexOf('var QP =')>=0?source.indexOf('var QP ='):source.indexOf('var QP=');
 const end=source.indexOf('var JUt',start);assert.ok(start>=0&&end>start,'Actual Core TOML helpers exist');
 const code=source.slice(start,end);
 function fixture(name,env={}){const root=path.join(run,file+'-'+name),dirname=path.join(root,'core/binary/out'),home=path.join(root,'own-cli-home');fs.mkdirSync(dirname,{recursive:true});return {root,dirname,home,ctx:vm.createContext({process:{env},__dirname:dirname,AR:fs,aL:path,mc:()=>home,m(){}})};}
 function template(target,text){fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,text);}
 test(file+': explicit owned resource template has priority over legacy layouts',()=>{const f=fixture('priority');const owned=path.join(f.root,'resources');f.ctx.process.env.GAMECOWORK_CLI_RESOURCE_DIR=owned;template(path.join(owned,'builtin-agents/unity-insight.toml'),'OWN_RESOURCE\n[run]\nmax_turns = 15\n');template(path.resolve(f.dirname,'../../gamecowork-cli/builtin-agents/unity-insight.toml'),'LEGACY');vm.runInContext(code,f.ctx);assert.match(f.ctx.Ayi(),/^OWN_RESOURCE/);});
 test(file+': missing explicit template preserves actual legacy fallback',()=>{const f=fixture('fallback',{GAMECOWORK_CLI_RESOURCE_DIR:path.join(run,'missing')});template(path.join(f.dirname,'templates/unity-insight.toml'),'FALLBACK');vm.runInContext(code,f.ctx);assert.equal(f.ctx.Ayi(),'FALLBACK');});
 test(file+': nondefault workspace and user settings persist actual template and scope',()=>{const f=fixture('persistence');const owned=path.join(repo,'src/agent/resources');f.ctx.process.env.GAMECOWORK_CLI_RESOURCE_DIR=owned;vm.runInContext(code,f.ctx);const workspace=path.join(f.root,'project');assert.equal(f.ctx.cba(27,{scope:'workspace',workspaceDir:workspace}),27);assert.equal(f.ctx.cba(34,{scope:'user',workspaceDir:workspace}),34);const actual=fs.readFileSync(path.join(workspace,'.gamecowork-cli/agents/unity-insight.toml'),'utf8');assert.match(actual,/max_turns\s*=\s*27/);assert.match(actual,/Read-only Unity project analysis specialist/);assert.equal(f.ctx.LUt({scope:'workspace',workspaceDir:workspace}),27);assert.equal(f.ctx.LUt({scope:'user'}),34);});
 test(file+': default clears only scoped generated file and missing nondefault template stays an error',()=>{const f=fixture('error');vm.runInContext(code,f.ctx);const workspace=path.join(f.root,'project'),target=path.join(workspace,'.gamecowork-cli/agents/unity-insight.toml');template(target,'[run]\nmax_turns = 20\n');assert.equal(f.ctx.cba(15,{scope:'workspace',workspaceDir:workspace}),15);assert.ok(!fs.existsSync(target));assert.throws(()=>f.ctx.cba(27,{scope:'workspace',workspaceDir:workspace}),/Missing seed template/);assert.ok(!fs.existsSync(target));});
}
