const test=require('node:test'),assert=require('node:assert/strict'),catalog=require('../../src/core/binary/out/modules/providers/catalog.js');
const provider=protocol=>catalog.normalizeProvider({id:'owned',baseUrl:'http://127.0.0.1:1234',protocol,kinds:protocol==='ollama'?['chat']:['image']});
test('No model-name heuristics grant dimensions, quality, upscale, references or generation claims',()=>{const p=provider('openai-images'),rows=catalog.normalizeModels(['high-4k-upscale-pro'],p);assert.equal(rows[0].capabilities.upscale.status,'unknown');assert.deepEqual(rows[0].capabilities.size.choices,[]);assert.equal(rows[0].stableStudioId,catalog.studioId(p.id,'high-4k-upscale-pro'));assert.throws(()=>catalog.normalizeCapabilities({size:{status:'supported',evidence:'unknown',choices:['4K']}}));assert.throws(()=>catalog.normalizeCapabilities({quality:{status:'supported',evidence:'manual',choices:['high'],requestField:'model'}}));});
test('HTTP LAN and credentials in baseURL need separate explicit boundaries',()=>{assert.throws(()=>catalog.baseUrl('http://192.168.1.5'));assert.equal(catalog.baseUrl('http://192.168.1.5:8188',true),'http://192.168.1.5:8188');for(const value of ['http://0300.0250.1.1','http://8.8.8.8','https://u:secret@example.com','https://example.com?key=secret','https://example.com#secret'])assert.throws(()=>catalog.baseUrl(value,true));});
test('Ollama model directory uses GET native tags instead of starting inference',async()=>{const seen=[];const reply=await catalog.fetchCatalog(provider('ollama'),'',async(url,init)=>{seen.push({url,method:init.method});return new Response(JSON.stringify({models:[{name:'owned:latest'}]}));});assert.deepEqual(reply.rows,[{id:'owned:latest'}]);assert.equal(seen[0].url,'http://127.0.0.1:1234/api/tags');assert.equal(seen[0].method,'GET');});
test('ComfyUI node schemas and model-file folders are kept distinct, without prompt or interrupt calls',async()=>{const seen=[];const reply=await catalog.fetchCatalog(provider('comfyui'),'',async(url,init)=>{seen.push(url);const body=url.endsWith('/object_info')?{CLIPTextEncode:{input:{}}}:url.endsWith('/models')?['checkpoints']:['own-model.safetensors'];assert.equal(init.method,'GET');return new Response(JSON.stringify(body));});assert.equal(reply.catalogType,'model-files');assert.deepEqual(reply.nodeTypes,['CLIPTextEncode']);assert.equal(reply.rows[0].id,'checkpoints/own-model.safetensors');assert.equal(seen.length,3);assert.ok(!seen.some(url=>/prompt|interrupt/.test(url)));});
test('Invalid and paginated directories do not become complete; redirects do not follow credentials',async()=>{for(const body of [{data:[{id:'a'},{id:'a'}]},{data:[{id:'a'}],has_more:true}]){if(body.has_more)await assert.rejects(()=>catalog.fetchCatalog(provider('openai-images'),'own',async()=>new Response(JSON.stringify(body))),/paginated/);else assert.throws(()=>catalog.normalizeModels(body.data,provider('openai-images')),/duplicate/);}await assert.rejects(()=>catalog.fetchCatalog(provider('openai-images'),'own',async(_url,init)=>{assert.equal(init.redirect,'manual');return new Response('',{status:302,headers:{Location:'https://example.com'}});}),/HTTP 302/);});
test('Every explicit next-page/total mismatch marker prevents a partial catalog replacing known models',async()=>{for(const marker of [{nextPage:'cursor'},{nextCursor:'cursor'},{links:{next:'/models?page=2'}},{pagination:{has_more:true}},{total:2},{total_count:2},{meta:{total:2}},{pagination:{total:2}}])await assert.rejects(()=>catalog.fetchCatalog(provider('openai-images'),'own',async()=>new Response(JSON.stringify({data:[{id:'a'}],...marker}))),/paginated/);});
test('Malformed or oversized ComfyUI node and folder catalogs are rejected before workflow execution',async()=>{for(const info of [{['bad\nnode']:{}},Object.fromEntries(Array.from({length:4097},(_,index)=>['node'+index,{}]))])await assert.rejects(()=>catalog.fetchCatalog(provider('comfyui'),'',async url=>new Response(JSON.stringify(url.endsWith('/object_info')?info:[]))),/invalid node/);});
test('Meaningful scene output requirements include exact target resolution and ratio without rewriting original wording',()=>{const original='A cozy game-development studio overlooking a rainy city, with a wooden desk, a warm task lamp, sketchbooks and a small plant.';const composed=catalog.composeImagePrompt(original,{resolutionHint:'2048x1152',aspectRatioHint:'16:9'});assert.ok(composed.startsWith(original+'\n\n'));assert.match(composed,/2048 x 1152 pixels/);assert.match(composed,/aspect ratio: 16:9/);assert.equal(catalog.composeImagePrompt(original,{resolutionHint:'auto',aspectRatioHint:'auto'}),original);});
test('Only explicitly valid requested dimensions/ratios are composed; API fallback and conflict checks are deterministic',()=>{const original='An isometric village market at sunrise with several stalls and cobblestone lanes.';for(const spec of [{resolutionHint:'2048x1152',aspectRatioHint:'1:1'},{resolutionHint:'2047x1152'},{resolutionHint:'4096x2048'},{resolutionHint:'3840x3840'},{aspectRatioHint:'9:1'},{aspectRatioHint:'100:99'}])assert.throws(()=>catalog.composeImagePrompt(original,spec));const fallback=catalog.composeImagePrompt(original,{size:'1536x1024',aspectRatio:'3:2'});assert.match(fallback,/1536 x 1024 pixels/);assert.match(fallback,/aspect ratio: 3:2/);assert.match(catalog.composeImagePrompt(original,{resolutionHint:'auto',aspectRatioHint:'9:16'}),/aspect ratio: 9:16/);assert.ok(!catalog.composeImagePrompt(original,{resolutionHint:'auto',aspectRatioHint:'9:16'}).includes('pixels'));assert.equal(catalog.composeImagePrompt(original,{size:'auto',aspectRatio:'auto'}),original);});
test('Image size policy defaults only on the exact normalized operator endpoint, while explicit opt-out and foreign defaults stay intact',()=>{const source={id:'another-id',protocol:'openai-images',baseUrl:'https://XCAI.PRO:443/v1/'};const operator=catalog.normalizeProvider(source);assert.equal(operator.imageSizePolicy,'openai-size');assert.equal(catalog.imageSizePolicyInfo(operator).evidence,'documented');assert.equal(catalog.imageSizePolicyInfo(operator).actual4kTested,false);assert.equal(catalog.imageSizePolicyInfo(operator).constraints.minPixels,655360);for(const baseUrl of ['https://other.example/v1','https://direct.xcai.pro/v1','https://xcai.pro/v2','https://xcai.pro/v1/other'])assert.equal(catalog.normalizeProvider({...source,baseUrl}).imageSizePolicy,'prompt-only');const optOut=catalog.normalizeProvider({...source,imageSizePolicy:'prompt-only'});assert.equal(catalog.normalizeProvider({id:optOut.id,name:'Renamed'},optOut).imageSizePolicy,'prompt-only');assert.equal(catalog.normalizeProvider({...source,baseUrl:'https://other.example/v1'},operator).imageSizePolicy,'prompt-only');assert.equal(catalog.imageSizePolicyInfo(catalog.normalizeProvider({...source,baseUrl:'https://other.example/v1',imageSizePolicy:'openai-size'})).evidence,'manual');for(const policy of ['4k',true,{}])assert.throws(()=>catalog.normalizeProvider({...source,imageSizePolicy:policy}),/policy/);assert.throws(()=>catalog.normalizeProvider({...source,protocol:'openai-chat',imageSizePolicy:'openai-size'}),/Images provider/);assert.equal(catalog.normalizeProvider({id:operator.id,protocol:'openai-chat',kinds:['chat']},operator).imageSizePolicy,undefined);assert.equal(catalog.unknownCapabilities().size.status,'unknown');});
test('Published rounded size/nominal-ratio tuples are accepted only through the internal OpenAI size policy context',()=>{const original='A fantasy harbor with colorful market stalls, weathered stone steps and a hilltop windmill.';let count=0;for(const presets of Object.values(catalog.OPENAI_IMAGE_SIZE_PRESETS))for(const [aspectRatioHint,resolutionHint] of Object.entries(presets)){count++;catalog.imageResolution(resolutionHint,655360);const result=catalog.composeImagePrompt(original,{resolutionHint,aspectRatioHint},{imageSizePolicy:'openai-size'});assert.match(result,new RegExp(resolutionHint.replace('x',' x ')+' pixels'));assert.ok(result.includes('aspect ratio: '+aspectRatioHint+'.'));}assert.equal(count,27);for(const context of [undefined,{imageSizePolicy:'prompt-only'}])assert.throws(()=>catalog.composeImagePrompt(original,{resolutionHint:'2048x1360',aspectRatioHint:'3:2'},context),/conflict/);for(const spec of [{resolutionHint:'2048x1360',aspectRatioHint:'2:3'},{resolutionHint:'2048x1344',aspectRatioHint:'3:2'},{resolutionHint:'3312x2496',aspectRatioHint:'4:3'}])assert.throws(()=>catalog.composeImagePrompt(original,spec,{imageSizePolicy:'openai-size'}),/conflict/);assert.throws(()=>catalog.imageResolution('512x512',655360),/limits/);assert.deepEqual(catalog.imageResolution('1024x640',655360),{width:1024,height:640,value:'1024x640'});});
test('All 27 new presets satisfy the native pixel limits and exact rational ratios without changing the eight historical rounded tuples',()=>{
  let count=0,changed=0;
  for(const [tier,presets]of Object.entries(catalog.OPENAI_IMAGE_EXACT_SIZE_PRESETS))for(const [ratio,size]of Object.entries(presets)){
    const {width,height}=catalog.imageResolution(size,655360),[a,b]=ratio.split(':').map(Number);count++;assert.equal(width*b,height*a,tier+' '+ratio);
    if(size!==catalog.OPENAI_IMAGE_SIZE_PRESETS[tier][ratio])changed++;
    const prompt=catalog.composeImagePrompt('A game landscape',{size,aspectRatio:ratio});assert.match(prompt,new RegExp(size.replace('x',' x ')+' pixels'));assert.ok(!prompt.includes('rounding'));
  }
  assert.equal(count,27);assert.equal(changed,8);assert.equal(catalog.OPENAI_IMAGE_SIZE_PRESETS['2k']['3:2'],'2048x1360');assert.equal(catalog.OPENAI_IMAGE_SIZE_PRESETS['4k']['21:9'],'3840x1648');assert.ok(Object.isFrozen(catalog.OPENAI_IMAGE_EXACT_SIZE_PRESETS['4k']));
});
test('Auto hints do not erase concrete API dimensions or ratios, and conflicting explicit aliases fail consistently',()=>{
  const original='A game landscape',prompt=catalog.composeImagePrompt(original,{size:'1536x1024',resolutionHint:'auto',aspectRatio:'3:2',aspectRatioHint:'auto'});assert.match(prompt,/1536 x 1024 pixels/);assert.match(prompt,/aspect ratio: 3:2/);
  const equivalent=catalog.composeImagePrompt(original,{size:'1536x1024',aspectRatio:'6:4',aspectRatioHint:'3:2'});assert.match(equivalent,/aspect ratio: 3:2/);
  for(const context of [undefined,{imageSizePolicy:'openai-size'}])for(const spec of [{size:'1536x1024',resolutionHint:'2048x1152'},{aspectRatio:'1:1',aspectRatioHint:'16:9'},{size:'1536x1024',aspectRatio:'16:9',aspectRatioHint:'auto'},{size:'landscape',resolutionHint:'1536x1024'},{aspectRatio:'landscape',aspectRatioHint:'16:9'}])assert.throws(()=>catalog.composeImagePrompt(original,spec,context),/conflict/);
});
test('Explicit old rounded tuple replay describes its true pixel ratio instead of claiming the nominal ratio is exact',()=>{
  const spec={size:'2048x1360',aspectRatio:'3:2',aspectRatioHint:'auto'},context={imageSizePolicy:'openai-size'},prompt=catalog.composeImagePrompt('A game landscape',spec,context);assert.match(prompt,/nominal image aspect ratio: 3:2/);assert.match(prompt,/exact pixel aspect ratio 128:85/);assert.ok(!prompt.includes('Required final image aspect ratio: 3:2.'));assert.equal(catalog.imageOutputRequirements(spec,context).rounded,true);
});
