import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';import {createRequire} from 'node:module';
import {startAssetGenerationProvider} from '../fixtures/asset-generation-provider-fixture.mjs';
const require=createRequire(import.meta.url),{createAssetService}=require('../../src/core/binary/out/modules/generation/service.js'),{createProviderRegistry}=require('../../src/core/binary/out/modules/providers/registry.js'),{createCodelyGeneratorApi}=require('../../src/core/binary/out/modules/generation/codely-api.js');
const root=path.resolve('F:/AI/AgentMake/CyberSoftwares/GameCowork/codelyreversebackup/work/2026-10-07-thirdparty-live/contracts-'+randomUUID()),master=randomBytes(32),seen=[];
const seal=async bytes=>{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',master,iv),data=Buffer.concat([cipher.update(bytes),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]);};
const unseal=async bytes=>{const cipher=createDecipheriv('aes-256-gcm',master,bytes.subarray(0,12));cipher.setAuthTag(bytes.subarray(12,28));return Buffer.concat([cipher.update(bytes.subarray(28)),cipher.final()]);};
let peer,asset,registry,configuration;let models=['gpt-image-2','gpt-image-2.5-flare','gpt-image-2.5-sunburst'];
const fetcher=async(url,init)=>{assert.equal(init.method,'GET');seen.push({url,method:init.method});return new Response(JSON.stringify({data:models.map(id=>({id}))}),{headers:{'Content-Type':'application/json'}});};
const open=(overrides={})=>{asset=createAssetService({root:path.join(root,'assets'),pollIntervalMs:10,requestTimeoutMs:1000});registry=createProviderRegistry({root:path.join(root,'registry'),assetService:asset,fetch:fetcher,seal,unseal,...overrides});};
const done=async id=>{for(let n=0;n<500;n++){const {task}=await asset.dispatch('generator/getTask',{taskId:id});if(['completed','failed','interrupted'].includes(task.status))return task;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Owned task timeout');};
test.before(async()=>{peer=await startAssetGenerationProvider({root,plans:{OWNED_HOLD_RESTART:{kind:'video',pendingPolls:10000},OWNED_CREATE_UNKNOWN:{kind:'video',holdCreate:true}}});open();configuration={id:'owned-images',name:'Owned images',baseUrl:peer.baseUrl,protocol:'openai-images',kinds:['image'],authMode:'bearer',apiKey:peer.apiKey};});
test.after(async()=>{await registry?.close();await asset?.close();await peer?.close();});
test('Provider public DTO, durable registry and projected Asset Service never contain key or plaintext copy',async()=>{const reply=await registry.dispatch('save',{provider:configuration});assert.equal(reply.provider.apiKeyConfigured,true);assert.equal(JSON.stringify(reply).includes(peer.apiKey),false);assert.equal(fs.readFileSync(path.join(root,'registry','registry.json'),'utf8').includes(peer.apiKey),false);assert.equal(fs.readFileSync(path.join(root,'assets','providers.json'),'utf8').includes(peer.apiKey),false);const stored=JSON.parse(fs.readFileSync(path.join(root,'assets','providers.json')));assert.equal(stored['managed_owned-images']._key,undefined);assert.equal(stored['managed_owned-images']._managedRegistryRef,'owned-images');});
test('Catalog GET reads every explicit upstream model without fabricating resolution or quality',async()=>{const reply=await registry.dispatch('syncModels',{providerId:configuration.id});assert.equal(reply.provider.catalogReady,true);assert.equal(reply.models.length,3);assert.ok(reply.models.every(model=>model.generationAvailable&&model.capabilities.size.status==='unknown'&&model.capabilities.quality.choices.length===0));assert.equal(seen.length,1);assert.equal(peer.requests.length,0);});
test('Public generation rejects unknown advanced controls and forged model/provider before any POST',async()=>{const model=registry.modelDescriptors()[0],payload={studioModelId:model.id,model:model.model,prompt:'OWNED'};for(const change of [{size:'1024x1024'},{quality:'high'},{providerId:'other'},{model:'forged'},{imageUrls:['http://localhost/input']},{n:8}])await assert.rejects(()=>registry.createImageTask(model.id,{...payload,...change},'workspace-a'));await assert.rejects(()=>asset.dispatch('generator/createTask',{providerId:'managed_owned-images',kind:'image',prompt:'Bypass'}),/internal registry/);assert.equal(peer.requests.length,0);});
test('Default sync image request binds actual Provider/model, fixes count one and verifies artifact bytes',async()=>{const model=registry.modelDescriptors()[0],reply=await registry.createImageTask(model.id,{studioModelId:model.id,model:model.model,prompt:'OWNED_DEFAULT'},'workspace-a'),task=await done(reply.task.id);assert.equal(task.status,'completed');assert.equal(task.managedStudioId,model.id);assert.equal(task.parameters.studioModelId,model.id);assert.equal(task.artifacts[0].sha256,peer.media.png.sha256);const request=peer.requests.at(-1);assert.deepEqual(request.body,{model:model.model,prompt:'OWNED_DEFAULT',n:1});assert.equal(request.authorized,true);assert.equal(JSON.stringify(task).includes(peer.apiKey),false);});
test('Explicit capabilities constrain controls; trusted probe remains separate from public dispatch',async()=>{const model=registry.modelDescriptors()[0];await registry.dispatch('setModelCapabilities',{providerId:configuration.id,modelId:model.model,capabilities:{size:{status:'supported',evidence:'manual',choices:['1536x1024'],source:'Owned declared fixture'},quality:{status:'supported',evidence:'tested',choices:['low']}}});let reply=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:'OWNED_CAPS',size:'1536x1024',quality:'low'},'workspace-a');assert.equal((await done(reply.task.id)).status,'completed');assert.equal(peer.requests.at(-1).body.size,'1536x1024');await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'OWNED_BAD',size:'4096x4096'},''));await assert.rejects(()=>registry.dispatch('probe',{studioModelId:model.id}));reply=await registry.createImageTaskFromProbe(model.id,{studioModelId:model.id,prompt:'OWNED_PROBE'},'workspace-a',{size:'1024x1536',quality:'high',outputFormat:'png'});assert.equal((await done(reply.task.id)).status,'completed');assert.equal(peer.requests.at(-1).body.quality,'high');assert.deepEqual(registry.resolveModel(model.id).capabilities.quality.choices,['low']);});
test('Restart unseals only privately; disappeared upstream models retain stable history lookup and become unavailable',async()=>{const first=registry.modelDescriptors()[0];await registry.close();await asset.close();open();await registry.ready;assert.equal((await registry.dispatch('list')).providers[0].apiKeyConfigured,true);assert.equal(registry.resolveModel(first.id).id,first.model);models=models.slice(1);await registry.dispatch('syncModels',{providerId:configuration.id});assert.equal(registry.resolveModel(first.id).available,false);await assert.rejects(()=>registry.createImageTask(first.id,{studioModelId:first.id,prompt:'NO_REPLAY'},''),/available/);assert.ok((await registry.dispatch('list')).models.some(model=>model.id===first.id&&!model.generationAvailable));});
test('LLM/Ollama/Comfy configurations do not grant a generation adapter; Comfy requires API-format explicit bindings',async()=>{for(const protocol of ['openai-chat','openai-responses','ollama']){const reply=await registry.dispatch('save',{provider:{id:'owned-'+protocol,name:protocol,baseUrl:peer.baseUrl,protocol,kinds:['chat'],authMode:'none'}});assert.equal(reply.provider.generationAvailable,false);}await assert.rejects(()=>registry.dispatch('save',{provider:{id:'bad-comfy',baseUrl:peer.baseUrl,protocol:'comfyui',workflow:{nodes:[]}}}),/API-format/);const reply=await registry.dispatch('save',{provider:{id:'owned-comfy',name:'Own workflow',baseUrl:peer.baseUrl,protocol:'comfyui',kinds:['image'],workflow:{graph:{'1':{class_type:'CLIPTextEncode',inputs:{text:'own prompt'}}},bindings:{prompt:{nodeId:'1',input:'text'}}}}});assert.equal(reply.provider.generationAvailable,false);assert.equal(reply.provider.workflow.bindings.prompt.input,'text');});
test('Delete tombstones descriptor history and removes only that Provider secret',async()=>{const old=registry.modelDescriptors().find(model=>model.providerId===configuration.id),reference=JSON.parse(fs.readFileSync(path.join(root,'registry','registry.json'))).providers[configuration.id]._credentialRef;await registry.dispatch('delete',{providerId:configuration.id});assert.equal(fs.existsSync(path.join(root,'registry',reference)),false);assert.equal(registry.resolveModel(old.id).providerDeleted,true);assert.ok(!(await registry.dispatch('list')).providers.some(provider=>provider.id===configuration.id));});
test('Generic REST uses configured video/model kind and original task polling, not an image placeholder',async()=>{for(const kind of ['video','model']){const providerId='own-'+kind;const reply=await registry.dispatch('save',{provider:{id:providerId,name:'Owned '+kind,baseUrl:peer.baseUrl,protocol:'generic-rest-task',kinds:[kind],authMode:'bearer',apiKey:peer.apiKey,adapter:{create:{method:'POST',path:'/tasks',bodyTemplate:{kind:'{{kind}}',model:'{{model}}',prompt:'{{prompt}}',parameters:'{{parameters}}'}},poll:{method:'GET',path:'/tasks/{{taskId}}'},cancel:null}}});assert.equal(reply.provider.generationAvailable,false);await registry.dispatch('syncModels',{providerId});const model=registry.modelDescriptors().find(model=>model.providerId===providerId);assert.equal(model.kind,kind);assert.equal(model.generationAvailable,true);const created=await registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:'OWNED_GENERIC_'+kind,parameters:{duration:1}},'workspace-kind');const task=await done(created.task.id);assert.equal(task.status,'completed');assert.equal(task.kind,kind);assert.ok(task.artifacts.some(artifact=>artifact.kind===kind));}});
test('Manual updates cannot forge tested evidence; verified in-process records remain separate',async()=>{const model=registry.modelDescriptors().find(model=>model.providerId==='own-video');await registry.dispatch('setModelCapabilities',{providerId:model.providerId,modelId:model.model,capabilities:{quality:{status:'supported',evidence:'tested',choices:['own-level']}}});assert.equal(registry.resolveModel(model.id).capabilities.quality.evidence,'manual');await registry.recordModelCapabilities({providerId:model.providerId,modelId:model.model,capabilities:{quality:{status:'supported',evidence:'tested',choices:['own-level'],source:'Owned isolated fixture'}}});assert.equal(registry.resolveModel(model.id).capabilities.quality.evidence,'tested');});
test('A linked durable registry rolls back new encrypted credentials and projected Provider',async()=>{const file=path.join(root,'registry','registry.json'),linked=path.join(root,'registry-linked.json'),before=fs.readFileSync(file);fs.linkSync(file,linked);try{await assert.rejects(()=>registry.dispatch('save',{provider:{...configuration,id:'own-failed-save'}}),/Linked/);assert.deepEqual(fs.readFileSync(linked),before);assert.equal(fs.existsSync(path.join(root,'registry','own-failed-save.vault')),false);assert.ok(!(await asset.dispatch('generator/listProviders')).providers.some(provider=>provider.id==='managed_own-failed-save'));}finally{fs.unlinkSync(linked);}});
test('Known managed remote ID waits for private vault readiness and resumes only GET to the same recorded task',async()=>{const model=registry.modelDescriptors().find(model=>model.providerId==='own-video'),created=await registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:'OWNED_HOLD_RESTART'},'workspace-restart');let remote;for(let n=0;n<100;n++){remote=[...peer.tasks.values()].find(task=>task.input.prompt==='OWNED_HOLD_RESTART');if(remote&&peer.requests.some(row=>row.method==='GET'&&row.taskId===remote.id))break;await new Promise(resolve=>setTimeout(resolve,10));}assert.ok(remote);const count=()=>peer.requests.filter(row=>row.method==='GET'&&row.taskId===remote.id).length;const before=count();await registry.close();await asset.close();open({unseal:async bytes=>{await new Promise(resolve=>setTimeout(resolve,60));return unseal(bytes);}});await new Promise(resolve=>setTimeout(resolve,20));assert.equal(count(),before);await registry.ready;for(let n=0;n<100&&count()===before;n++)await new Promise(resolve=>setTimeout(resolve,10));assert.ok(count()>before);remote.plan.pendingPolls=0;assert.equal((await done(created.task.id)).status,'completed');assert.equal(peer.requests.filter(row=>row.method==='POST'&&row.body.prompt==='OWNED_HOLD_RESTART').length,1);});
test('Declared request-field choices cannot replace model/count; API ratio is also composed into request while original history stays exact',async()=>{const saved=await registry.dispatch('save',{provider:{...configuration,id:'own-ratio'}});await registry.dispatch('syncModels',{providerId:saved.provider.id});const model=registry.modelDescriptors().find(model=>model.providerId==='own-ratio');for(const requestField of ['n','model','prompt','authorization','headers','api_key','stream'])await assert.rejects(()=>registry.dispatch('setModelCapabilities',{providerId:model.providerId,modelId:model.model,capabilities:{size:{status:'supported',evidence:'manual',choices:['own'],requestField}}}),/request field/);await registry.recordModelCapabilities({providerId:model.providerId,modelId:model.model,capabilities:{aspectRatio:{status:'supported',evidence:'documented',choices:['16:9'],requestField:'aspect_ratio',source:'Owned protocol fixture'}}});const original='Original user prompt';const created=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:original,aspectRatio:'16:9'},'workspace-ratio');const task=await done(created.task.id);const expected=original+'\n\n[Image output requirements]\nRequired final image aspect ratio: 16:9.\nCompose the whole scene for these output requirements.';assert.equal(task.prompt,original);assert.equal(task.parameters.prompt,original);assert.equal(task.executionPrompt,expected);assert.equal(peer.requests.at(-1).body.prompt,expected);assert.equal(peer.requests.at(-1).body.aspect_ratio,'16:9');assert.equal(peer.requests.at(-1).body.n,1);});
test('Unknown managed POST result survives restart without any automatic second create',async()=>{const provider=(await registry.dispatch('list')).providers.find(provider=>provider.id==='own-video');await registry.dispatch('save',{provider:{...provider,requestTimeoutMs:1000}});const model=registry.modelDescriptors().find(model=>model.providerId==='own-video');const created=await registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:'OWNED_CREATE_UNKNOWN'},'workspace-unknown'),task=await done(created.task.id);assert.equal(task.status,'interrupted');assert.equal(task.mayContinue,true);const creates=()=>peer.requests.filter(row=>row.method==='POST'&&row.body.prompt==='OWNED_CREATE_UNKNOWN').length;assert.equal(creates(),1);await registry.close();await asset.close();open();await registry.ready;await new Promise(resolve=>setTimeout(resolve,50));assert.equal((await asset.dispatch('generator/getTask',{taskId:task.id})).task.status,'interrupted');assert.equal(creates(),1);});
test('A model generation capability marked unsupported disables descriptor and execution before transport',async()=>{const model=registry.modelDescriptors().find(model=>model.providerId==='own-ratio'),before=peer.requests.length;await registry.recordModelCapabilities({providerId:model.providerId,modelId:model.model,capabilities:{generation:{status:'unsupported',evidence:'tested',choices:[],source:'Owned explicit result'}}});assert.equal(registry.modelDescriptors().find(row=>row.id===model.id).generationAvailable,false);await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'Must remain blocked'},''),/available/);assert.equal(peer.requests.length,before);});
test('Updating an existing key rolls back vault pointer, metadata and private cache on failed registry commit',async()=>{const file=path.join(root,'registry','registry.json'),linked=path.join(root,'registry-update-linked.json'),before=fs.readFileSync(file),stored=JSON.parse(before).providers['own-model'],ref=stored._credentialRef,oldVault=fs.readFileSync(path.join(root,'registry',ref)),oldFiles=fs.readdirSync(path.join(root,'registry')).filter(name=>name.endsWith('.vault')).sort();fs.linkSync(file,linked);try{await assert.rejects(()=>registry.dispatch('save',{provider:{id:'own-model',apiKey:'owned-rotated-key-'+randomUUID()}}),/Linked/);assert.deepEqual(fs.readFileSync(linked),before);assert.deepEqual(fs.readFileSync(path.join(root,'registry',ref)),oldVault);assert.deepEqual(fs.readdirSync(path.join(root,'registry')).filter(name=>name.endsWith('.vault')).sort(),oldFiles);assert.equal((await registry.dispatch('list')).providers.find(provider=>provider.id==='own-model').apiKeyConfigured,true);const model=registry.modelDescriptors().find(model=>model.providerId==='own-model');const created=await registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:'OWNED_AFTER_FAILED_ROTATION'},'workspace-old-key');assert.equal((await done(created.task.id)).status,'completed');assert.equal(peer.requests.find(row=>row.body.prompt==='OWNED_AFTER_FAILED_ROTATION').authorized,true);}finally{fs.unlinkSync(linked);}});
test('Uncommitted immutable encrypted revision cannot replace old credentials after a process restart',async()=>{const directory=path.join(root,'registry'),metadataFile=path.join(directory,'registry.json'),metadata=JSON.parse(fs.readFileSync(metadataFile)),stored=metadata.providers['own-model'],oldRef=stored._credentialRef;const orphan='credential_own-model_'+randomUUID()+'.vault';fs.writeFileSync(path.join(directory,orphan),await seal(Buffer.from('owned-uncommitted-key-'+randomUUID())));await registry.close();await asset.close();open();await registry.ready;assert.equal(JSON.parse(fs.readFileSync(metadataFile)).providers['own-model']._credentialRef,oldRef);const model=registry.modelDescriptors().find(model=>model.providerId==='own-model');const created=await registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:'OWNED_AFTER_ORPHAN_REVISION'},'workspace-old-key');assert.equal((await done(created.task.id)).status,'completed');assert.equal(peer.requests.find(row=>row.body.prompt==='OWNED_AFTER_ORPHAN_REVISION').authorized,true);});
test('Legacy candidate id.vault records load without plaintext migration or changing historical descriptors',async()=>{await registry.close();await asset.close();const file=path.join(root,'registry','registry.json'),metadata=JSON.parse(fs.readFileSync(file)),stored=metadata.providers['own-model'],legacy=stored.id+'.vault';fs.renameSync(path.join(root,'registry',stored._credentialRef),path.join(root,'registry',legacy));delete stored._credentialRef;fs.writeFileSync(file,JSON.stringify(metadata));open();await registry.ready;assert.equal((await registry.dispatch('list')).providers.find(provider=>provider.id==='own-model').apiKeyConfigured,true);assert.equal(registry.modelDescriptors().find(model=>model.providerId==='own-model').model,stored.models[0].id);});
test('Secrets in names, foreign metadata values, JSON property names and ComfyUI node directories are rejected',async()=>{const second='owned-with-symbols+/='+randomUUID();await registry.dispatch('save',{provider:{id:'owned-secret-guard',name:'Own credential',baseUrl:peer.baseUrl,protocol:'openai-chat',kinds:['chat'],authMode:'bearer',apiKey:second}});for(const name of [peer.apiKey,second,encodeURIComponent(second)])await assert.rejects(()=>registry.dispatch('save',{provider:{id:'owned-leak-attempt',name,baseUrl:peer.baseUrl,protocol:'openai-chat'}}),/credentials/);await assert.rejects(()=>registry.dispatch('save',{provider:{id:'owned-json-key-leak',baseUrl:peer.baseUrl,protocol:'generic-rest-task',adapter:{create:{method:'POST',path:'/tasks',bodyTemplate:{[second]:'x'}}}}}),/credentials/);await registry.dispatch('save',{provider:{id:'owned-node-catalog-leak',name:'Own nodes',baseUrl:peer.baseUrl,protocol:'comfyui',kinds:['image'],authMode:'bearer',apiKey:second}});const alternate=createProviderRegistry({root:path.join(root,'registry-separate'),assetService:asset,seal,unseal,fetch:async url=>new Response(JSON.stringify(url.endsWith('/object_info')?{[second]:{input:{}}}:[]))});try{await alternate.dispatch('save',{provider:{id:'owned-node-check',baseUrl:peer.baseUrl,protocol:'comfyui',authMode:'bearer',apiKey:second}});await assert.rejects(()=>alternate.dispatch('syncModels',{providerId:'owned-node-check'}),/credentials/);assert.equal(fs.readFileSync(path.join(root,'registry-separate','registry.json'),'utf8').includes(second),false);}finally{await alternate.close();}});
test('Actual Asset Service headers never attach managed Bearer or custom-header credentials across origins',()=>{const source=fs.readFileSync(new URL('../../src/core/binary/out/modules/generation/service.js',import.meta.url),'utf8'),line=source.split(/\r?\n/).find(line=>line.trimStart().startsWith('function headers(provider, url, json = false)'));assert.ok(line);const key='owned-header-boundary-'+randomUUID(),context=vm.createContext({URL,providerKey:()=>key});const headers=vm.runInContext('('+line.trim()+')',context);for(const authMode of ['bearer','header']){const provider={baseUrl:'https://owned-api.example/v1',authMode,apiKeyHeader:'X-Owned-Key'};const same=headers(provider,new URL('https://owned-api.example/v1/images/generations'));assert.equal(authMode==='bearer'?same.Authorization:same['X-Owned-Key'],authMode==='bearer'?'Bearer '+key:key);for(const url of ['https://different-cdn.example/out.png','https://owned-api.example:8443/out.png','http://owned-api.example/out.png'])assert.equal(JSON.stringify(headers(provider,new URL(url),true)).includes(key),false);}});
test('Meaningful scene sends independent prompt resolution/ratio requirements with unknown API capabilities, preserves braces and durable original history',async()=>{await registry.dispatch('save',{provider:{...configuration,id:'own-prompt-hints'}});await registry.dispatch('syncModels',{providerId:'own-prompt-hints'});const model=registry.modelDescriptors().find(model=>model.providerId==='own-prompt-hints');assert.equal(model.capabilities.size.status,'unknown');const original='A warmly lit game-development studio overlooking a rainy city: a wooden desk, sketchbooks, a brass task lamp and a small plant. Preserve the literal studio sign {{model}}.';const expected=original+'\n\n[Image output requirements]\nRequired final image resolution: 2048 x 1152 pixels.\nRequired final image aspect ratio: 16:9.\nCompose the whole scene for these output requirements.';const created=await registry.createImageTask(model.id,{studioModelId:model.id,model:model.model,prompt:original,resolutionHint:'2048x1152',aspectRatioHint:'16:9'},'workspace-scene');const task=await done(created.task.id);assert.equal(task.status,'completed');assert.equal(task.prompt,original);assert.equal(task.parameters.prompt,original);assert.equal(task.parameters.resolutionHint,'2048x1152');assert.equal(task.parameters.aspectRatioHint,'16:9');assert.equal(task.executionPrompt,expected);assert.deepEqual(peer.requests.at(-1).body,{model:model.model,prompt:expected,n:1});assert.ok(peer.requests.at(-1).body.prompt.includes('{{model}}'));const stored=JSON.parse(fs.readFileSync(path.join(root,'assets','tasks.json')))[task.id];assert.equal(stored._managedRequestPrompt,expected);assert.equal(typeof stored._managedOriginalPromptSha256,'string');assert.equal(stored._managedOriginalPromptSha256.length,64);assert.equal(stored._managedRequestPromptSha256.length,64);const before=peer.requests.length;await registry.close();await asset.close();open();await registry.ready;await new Promise(resolve=>setTimeout(resolve,30));const resumed=(await asset.dispatch('generator/getTask',{taskId:task.id})).task;assert.equal(resumed.prompt,original);assert.equal(resumed.executionPrompt,expected);assert.equal(peer.requests.length,before);});
test('Prompt hint conflicts, out-of-bounds sizes and public requestPrompt injection fail before generation',async()=>{const model=registry.modelDescriptors().find(model=>model.providerId==='own-prompt-hints'),before=peer.requests.length;for(const change of [{resolutionHint:'2048x1152',aspectRatioHint:'1:1'},{resolutionHint:'2047x1152'},{resolutionHint:'4096x2048'},{aspectRatioHint:'10:1'},{requestPrompt:'forged'}])await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'An isometric village market at sunrise.',...change},'workspace-conflict'));for(const change of [{executionPrompt:'forged'},{requestPrompt:'forged'},{_managedRequestPrompt:'forged'}])await assert.rejects(()=>asset.dispatch('generator/createTask',{providerId:'managed_own-prompt-hints',kind:'image',prompt:'forge',...change}),/internal entry point/);const video=registry.modelDescriptors().find(model=>model.providerId==='own-video');await assert.rejects(()=>registry.createGenerationTask(video.id,{studioModelId:video.id,prompt:'A walk through a market.',resolutionHint:'2048x1152'},''),/only supported for image/);assert.equal(peer.requests.length,before);});
test('Generic image parameters.prompt template receives resolved requirements once; a template omitting prompt binding is rejected',async()=>{const provider={id:'own-generic-hints',name:'Own custom image endpoint',baseUrl:peer.baseUrl,protocol:'generic-rest-task',kinds:['image'],authMode:'bearer',apiKey:peer.apiKey,adapter:{responseMode:'outputs',create:{method:'POST',path:'/images/generations',bodyTemplate:{model:'{{model}}',prompt:'{{parameters.prompt}}',n:1}},cancel:null,selectors:{outputs:'data'},outputSelectors:{url:'url',base64:'b64_json',mime:'',filename:''}}};await registry.dispatch('save',{provider});await registry.dispatch('syncModels',{providerId:provider.id});const model=registry.modelDescriptors().find(model=>model.providerId===provider.id),original='A peaceful forest cabin game background, with a stone path and misty trees; preserve {{not_a_template}} as lettering.';const created=await registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:original,resolutionHint:'1536x1024',aspectRatioHint:'3:2'},'workspace-custom-image');const task=await done(created.task.id);assert.equal(task.status,'completed');assert.equal(task.parameters.prompt,original);assert.equal(task.prompt,original);assert.equal(peer.requests.at(-1).body.prompt,task.executionPrompt);assert.ok(task.executionPrompt.includes('{{not_a_template}}'));assert.match(task.executionPrompt,/1536 x 1024 pixels/);const before=peer.requests.length;await registry.dispatch('save',{provider:{...provider,adapter:{...provider.adapter,create:{...provider.adapter.create,bodyTemplate:{model:'{{model}}',prompt:'A fixed literal',n:1}}}}});await assert.rejects(()=>registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:original,resolutionHint:'1536x1024'},''),/must send the task prompt/);assert.equal(peer.requests.length,before);});
test('Explicit OpenAI size policy sends actual API pixels without granting unknown quality, preserves prompt and decodes the real smaller artifact',async()=>{await registry.dispatch('save',{provider:{...configuration,id:'own-openai-size',imageSizePolicy:'openai-size'}});await registry.dispatch('syncModels',{providerId:'own-openai-size'});const model=registry.modelDescriptors().find(model=>model.providerId==='own-openai-size'),original='A hand-painted fantasy harbor at sunset, with timber docks, colorful market awnings and a windmill on the hill; preserve {{model}} lettering.';assert.equal(model.imageSizePolicy,'openai-size');assert.equal(model.imageSizePolicyInfo.evidence,'manual');assert.equal(model.capabilities.size.status,'unknown');assert.equal(model.capabilities.quality.status,'unknown');const made=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:original,resolutionHint:'3840x2160',aspectRatioHint:'16:9'},'workspace-size'),task=await done(made.task.id),request=peer.requests.at(-1);assert.equal(task.status,'completed');assert.equal(task.prompt,original);assert.equal(task.parameters.prompt,original);assert.equal(task.parameters.size,'3840x2160');assert.deepEqual(request.body,{model:model.model,prompt:task.executionPrompt,n:1,size:'3840x2160'});assert.ok(request.body.prompt.includes('{{model}}'));assert.match(request.body.prompt,/3840 x 2160 pixels/);assert.equal(task.artifacts[0].width,48);assert.equal(task.artifacts[0].height,32);assert.equal(task.artifacts[0].sha256,peer.media.png.sha256);assert.equal(registry.resolveModel(model.id).capabilities.size.status,'unknown');const fromApi=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:original,size:'2880x2880'},'workspace-size');assert.equal((await done(fromApi.task.id)).parameters.size,'2880x2880');assert.equal(peer.requests.at(-1).body.size,'2880x2880');const nominal=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:original,resolutionHint:'3520x2336',aspectRatioHint:'3:2'},'workspace-size');assert.equal((await done(nominal.task.id)).status,'completed');assert.equal(peer.requests.at(-1).body.size,'3520x2336');assert.match(peer.requests.at(-1).body.prompt,/aspect ratio: 3:2/);const defaultRequest=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:original,resolutionHint:'auto'},'workspace-size');await done(defaultRequest.task.id);assert.deepEqual(peer.requests.at(-1).body,{model:model.model,prompt:original,n:1});});
test('OpenAI size policy rejects API/target conflicts, forged policy context and unsupported tiers before transport',async()=>{const model=registry.modelDescriptors().find(model=>model.providerId==='own-openai-size'),before=peer.requests.length;for(const change of [{size:'1536x1024',resolutionHint:'3840x2160'},{size:'auto',resolutionHint:'3840x2160'},{size:'4096x4096'},{size:'2047x1152'},{resolutionHint:'2048x1360',aspectRatioHint:'2:3'},{resolutionHint:'2048x1344',aspectRatioHint:'3:2'},{resolutionHint:'3840x3840'},{size:'auto'},{quality:'high'},{resolution:'4k'},{imageSizePolicy:'openai-size'},{context:{imageSizePolicy:'openai-size'}},{createSpec:{method:'POST',path:'/images/generations'}}])await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'A forest ranger portrait with a longbow and detailed green cloak.',...change},'workspace-rejected'));assert.equal(peer.requests.length,before);});
test('Legacy operator metadata derives size policy on cold load without changing registry, credentials or completed historical requests',async()=>{await registry.dispatch('save',{provider:{...configuration,id:'own-xcai-legacy',baseUrl:'https://xcai.pro/v1'}});await registry.dispatch('syncModels',{providerId:'own-xcai-legacy'});const file=path.join(root,'registry','registry.json'),metadata=JSON.parse(fs.readFileSync(file)),stored=metadata.providers['own-xcai-legacy'],credentialFile=path.join(root,'registry',stored._credentialRef),credentialBytes=fs.readFileSync(credentialFile);delete stored.imageSizePolicy;fs.writeFileSync(file,JSON.stringify(metadata));const legacyBytes=fs.readFileSync(file),historyBytes=fs.readFileSync(path.join(root,'assets','tasks.json')),before=peer.requests.length;await registry.close();await asset.close();open();await registry.ready;const dto=(await registry.dispatch('list')).providers.find(provider=>provider.id==='own-xcai-legacy'),model=registry.modelDescriptors().find(model=>model.providerId===dto.id);assert.equal(dto.imageSizePolicy,'openai-size');assert.equal(dto.imageSizePolicyInfo.evidence,'documented');assert.equal(model.imageSizePolicyInfo.actual4kTested,false);assert.equal(model.imageSizePolicyInfo.constraints.minPixels,655360);assert.equal(model.capabilities.size.status,'unknown');assert.equal(dto.apiKeyConfigured,true);assert.deepEqual(fs.readFileSync(file),legacyBytes);assert.deepEqual(fs.readFileSync(credentialFile),credentialBytes);assert.deepEqual(fs.readFileSync(path.join(root,'assets','tasks.json')),historyBytes);await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'A cabin beside a misty lake.',resolutionHint:'512x512'},''),/limits/);assert.equal(peer.requests.length,before);await registry.dispatch('save',{provider:{id:dto.id,imageSizePolicy:'prompt-only'}});assert.deepEqual(fs.readFileSync(credentialFile),credentialBytes);await registry.close();await asset.close();open();await registry.ready;assert.equal((await registry.dispatch('list')).providers.find(provider=>provider.id===dto.id).imageSizePolicy,'prompt-only');assert.equal(registry.modelDescriptors().find(row=>row.id===model.id).imageSizePolicy,'prompt-only');assert.equal(peer.requests.length,before);});
test('Regenerating an old prompt-only target under an explicitly changed policy derives size only for the new task',async()=>{const model=registry.modelDescriptors().find(model=>model.providerId==='own-prompt-hints');await registry.dispatch('save',{provider:{id:model.providerId,imageSizePolicy:'prompt-only'}});const made=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:'A wooden desk with sketchbooks, a warm task lamp and a rainy city view.',resolutionHint:'2048x1152',aspectRatioHint:'16:9'},'workspace-replay'),previous=await done(made.task.id);assert.equal(peer.requests.at(-1).body.size,undefined);const historyFile=path.join(root,'assets','tasks.json'),oldBytes=JSON.stringify(JSON.parse(fs.readFileSync(historyFile))[previous.id]);await registry.dispatch('save',{provider:{id:model.providerId,imageSizePolicy:'openai-size'}});const nextMade=await registry.createImageTask(model.id,{...previous.parameters},previous.workspaceKey),next=await done(nextMade.task.id);assert.equal(next.parameters.size,'2048x1152');assert.equal(peer.requests.at(-1).body.size,'2048x1152');assert.equal(next.prompt,previous.prompt);assert.equal(JSON.stringify(JSON.parse(fs.readFileSync(historyFile))[previous.id]),oldBytes);assert.equal((await asset.dispatch('generator/getTask',{taskId:previous.id})).task.parameters.size,undefined);const before=peer.requests.length;await registry.close();await asset.close();open();await registry.ready;await new Promise(resolve=>setTimeout(resolve,30));assert.equal(peer.requests.length,before);assert.equal(JSON.stringify(JSON.parse(fs.readFileSync(historyFile))[previous.id]),oldBytes);});
test('An explicitly unsupported API size blocks public policy targets while defaults, trusted probes and unknown claims remain distinct',async()=>{const model=registry.modelDescriptors().find(model=>model.providerId==='own-openai-size'),before=peer.requests.length;await registry.recordModelCapabilities({providerId:model.providerId,modelId:model.model,capabilities:{size:{status:'unsupported',evidence:'tested',choices:[],source:'Owned explicit no-size fixture'}}});const prompt='An illustrated forest cabin beside a misty lake with a stone path and warm window light.';for(const change of [{resolutionHint:'3840x2160'},{size:'1536x1024'},{size:'auto'}])await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt,...change},'workspace-unsupported-size'),/该模型已标记不支持接口尺寸参数，请切换提示词策略或修改模型配置/);assert.equal(peer.requests.length,before);const defaultMade=await registry.createImageTask(model.id,{studioModelId:model.id,prompt,resolutionHint:'auto'},'workspace-unsupported-size');assert.equal((await done(defaultMade.task.id)).status,'completed');assert.equal(peer.requests.at(-1).body.size,undefined);const probeMade=await registry.createImageTaskFromProbe(model.id,{studioModelId:model.id,prompt,resolutionHint:'1536x1024'},'workspace-unsupported-size',{size:'1536x1024'});assert.equal((await done(probeMade.task.id)).status,'completed');assert.equal(peer.requests.at(-1).body.size,'1536x1024');assert.equal(registry.resolveModel(model.id).capabilities.size.status,'unsupported');await registry.recordModelCapabilities({providerId:model.providerId,modelId:model.model,capabilities:{size:{status:'unknown',evidence:'unknown',choices:[]}}});const unknownMade=await registry.createImageTask(model.id,{studioModelId:model.id,prompt,resolutionHint:'3840x2160'},'workspace-unknown-size');assert.equal((await done(unknownMade.task.id)).status,'completed');assert.equal(peer.requests.at(-1).body.size,'3840x2160');assert.equal(registry.resolveModel(model.id).capabilities.size.status,'unknown');});

test('Mixed REST directories preserve explicit per-model kinds after directory refresh and cold restoration',async()=>{
  const provider={id:'own-mixed-rest',name:'Own mixed media',baseUrl:peer.baseUrl,protocol:'generic-rest-task',kinds:['image','video','model'],authMode:'bearer',apiKey:peer.apiKey,adapter:{create:{method:'POST',path:'/tasks',bodyTemplate:{kind:'{{kind}}',model:'{{model}}',prompt:'{{prompt}}',parameters:'{{parameters}}'}},poll:{method:'GET',path:'/tasks/{{taskId}}'},cancel:null}};
  await registry.dispatch('save',{provider});await registry.dispatch('syncModels',{providerId:provider.id});
  const descriptor=registry.modelDescriptors().find(model=>model.providerId===provider.id),compatibility=createCodelyGeneratorApi({assetService:asset,providerRegistry:registry,getOfficial:()=>null});
  const reply=await compatibility.dispatch({method:'PUT',path:'/local/providers/'+provider.id+'/model-capabilities',body:{modelId:descriptor.model,kind:'video'},origin:peer.baseUrl});assert.equal(reply.status,200);assert.equal(reply.body.model.kind,'video');
  await registry.dispatch('syncModels',{providerId:provider.id});assert.equal(registry.resolveModel(descriptor.id).kind,'video');
  await assert.rejects(()=>registry.dispatch('setModelCapabilities',{providerId:provider.id,modelId:descriptor.model,kind:'audio'}),/Provider kinds/);
  const stored=fs.readFileSync(path.join(root,'registry','registry.json'));
  await registry.close();await asset.close();open();await registry.ready;assert.equal(registry.resolveModel(descriptor.id).kind,'video');assert.equal(registry.resolveModel(descriptor.id).stableStudioId,descriptor.id);assert.deepEqual(fs.readFileSync(path.join(root,'registry','registry.json')),stored);
  const created=await registry.createGenerationTask(descriptor.id,{studioModelId:descriptor.id,model:descriptor.model,prompt:'OWNED_MIXED_VIDEO',parameters:{duration:4,aspect_ratio:'9:16'}},'workspace-mixed');const task=await done(created.task.id);assert.equal(task.kind,'video');assert.equal(task.status,'completed');const submitted=peer.requests.find(row=>row.body.prompt==='OWNED_MIXED_VIDEO').body;assert.equal(submitted.kind,'video');assert.deepEqual(submitted.parameters,{duration:4,aspect_ratio:'9:16'});assert.equal(task.artifacts[0].mime,'video/mp4');
});

test('REST video sends original documented parameter names and JSON types, freezes their envelope and restores exact History drafts',async()=>{
  const provider={id:'own-video-fields',name:'Own documented video fields',baseUrl:peer.baseUrl,protocol:'generic-rest-task',kinds:['video'],authMode:'bearer',apiKey:peer.apiKey,adapter:{create:{method:'POST',path:'/tasks',bodyTemplate:{kind:'{{kind}}',model:'{{model}}',prompt:'{{prompt}}',resolution:'{{parameters.resolution}}',aspect_ratio:'{{parameters.aspect_ratio}}',seconds:'{{parameters.seconds}}',options:'{{parameters.options}}',keyframes:'{{parameters.keyframes}}',n:'{{parameters.n}}'}},poll:{method:'GET',path:'/tasks/{{taskId}}'},cancel:null}};
  await registry.dispatch('save',{provider});await registry.dispatch('syncModels',{providerId:provider.id});const model=registry.modelDescriptors().find(model=>model.providerId===provider.id),parameters={resolution:'1280x720',aspect_ratio:'16:9',seconds:4,options:{seed:27,enhance:false},keyframes:[{time:0,label:'start'},{time:4,label:'end'}],n:1},original='A slow camera move over a game harbor; preserve literal {{model}}.';
  const compatibility=createCodelyGeneratorApi({assetService:asset,providerRegistry:registry,getOfficial:()=>null}),created=await compatibility.dispatch({method:'POST',path:'/sso/generate',origin:peer.baseUrl,workspaceKey:'workspace-video-fields',body:{kind:model.id,data:{studioModelId:model.id,model:model.model,prompt:original,parameters}}});assert.equal(created.status,200);const task=await done(created.body.taskId);assert.equal(task.status,'completed');
  const request=peer.requests.find(row=>row.body.prompt===original);assert.deepEqual(request.body,{kind:'video',model:model.model,prompt:original,...parameters});assert.deepEqual(task.providerParameters,parameters);assert.equal(task.providerProtocol,'generic-rest-task');assert.equal(task.executionPrompt,undefined);assert.equal(task.artifacts[0].width,32);assert.equal(task.artifacts[0].height,32);assert.equal(task.artifacts[0].encodedWidth,32);assert.equal(task.artifacts[0].encodedHeight,32);assert.equal(task.artifacts[0].dimensionKind,'display');assert.equal(task.artifacts[0].dimensionsStatus,'known');
  const history=await compatibility.dispatch({method:'GET',path:'/task/'+task.id+'/status',origin:peer.baseUrl,workspaceKey:'workspace-video-fields'});assert.equal(history.status,200);assert.equal(history.body.category,'video');assert.deepEqual(history.body.input.data.parameters,parameters);assert.equal(history.body.input.data.prompt,original);assert.equal(history.body.output.data.artifacts[0].sha256,peer.media.mp4.sha256);assert.equal(history.body.output.data.artifacts[0].width,32);assert.equal(history.body.output.data.artifacts[0].dimensionKind,'display');assert.equal(history.body.output.data.artifacts[0].dimensionsSource,'mp4-video-track-header');
  const creates=peer.requests.filter(row=>row.method==='POST'&&row.body.prompt===original).length;await registry.close();await asset.close();open();await registry.ready;const after=createCodelyGeneratorApi({assetService:asset,providerRegistry:registry,getOfficial:()=>null}),restored=await after.dispatch({method:'GET',path:'/task/'+task.id+'/status',origin:peer.baseUrl,workspaceKey:'workspace-video-fields'});assert.deepEqual(restored.body.input.data.parameters,parameters);assert.deepEqual(restored.body.output.data.artifacts,history.body.output.data.artifacts);assert.equal(peer.requests.filter(row=>row.method==='POST'&&row.body.prompt===original).length,creates);
});

test('Selected REST parameters and known image controls omitted by a template reject before creating any task or issuing POST',async()=>{
  const provider={id:'own-rest-omitted',name:'Own incomplete template',baseUrl:peer.baseUrl,protocol:'generic-rest-task',kinds:['image','video'],authMode:'bearer',apiKey:peer.apiKey,adapter:{create:{method:'POST',path:'/tasks',bodyTemplate:{kind:'{{kind}}',model:'{{model}}',prompt:'{{prompt}}',options:'{{parameters.options.seed}}'}},poll:{method:'GET',path:'/tasks/{{taskId}}'},cancel:null}};
  await registry.dispatch('save',{provider});await registry.dispatch('syncModels',{providerId:provider.id});const model=registry.modelDescriptors().find(model=>model.providerId===provider.id);await registry.recordModelCapabilities({providerId:provider.id,modelId:model.model,capabilities:{size:{status:'supported',evidence:'manual',choices:['1536x1024']},aspectRatio:{status:'supported',evidence:'manual',choices:['3:2']}}});
  const beforeTasks=asset.getOwnedSnapshot().tasks.length,beforeRequests=peer.requests.length;
  for(const selected of [{parameters:{options:{seed:1},seconds:4}},{parameters:{options:{seed:1,enhance:false}}},{parameters:{options:{seed:1}},size:'1536x1024'},{parameters:{options:{seed:1}},aspectRatio:'3:2'}])await assert.rejects(()=>registry.createGenerationTask(model.id,{studioModelId:model.id,prompt:'Must not submit an ignored option',...selected},''),/does not send the selected service parameter/);
  assert.equal(asset.getOwnedSnapshot().tasks.length,beforeTasks);assert.equal(peer.requests.length,beforeRequests);
});

test('REST JSON requires an object and cannot silently override selected controls, model identity, prompt or contain credentials',async()=>{
  const model=registry.modelDescriptors().find(model=>model.providerId==='own-video-fields'),before=peer.requests.length;
  for(const parameters of [null,[],false,2,'{}',{model:'different'},{studioModelId:'different'},{prompt:'different'},{authorization:'must-not-store'},{options:{apiKey:'must-not-store'}}])await assert.rejects(()=>registry.createGenerationTask(model.id,{studioModelId:model.id,model:model.model,prompt:'Must not submit malformed JSON',parameters},''));
  for(const field of ['providerProtocol','providerParameters'])await assert.rejects(()=>asset.dispatch('generator/createTask',{providerId:'managed_'+model.providerId,kind:'video',prompt:'Forged profile',[field]:field==='providerProtocol'?'generic-rest-task':{seconds:4}}),/internal entry point/);
  assert.equal(peer.requests.length,before);
});

test('Explicit image request-field mappings survive API size policy and auto hints preserve the actual API requirements',async()=>{
  const provider={...configuration,id:'own-exact-fields',imageSizePolicy:'openai-size'};await registry.dispatch('save',{provider});await registry.dispatch('syncModels',{providerId:provider.id});const model=registry.modelDescriptors().find(model=>model.providerId===provider.id);
  await registry.recordModelCapabilities({providerId:provider.id,modelId:model.model,capabilities:{size:{status:'supported',evidence:'manual',choices:['1536x1024'],requestField:'resolution'},quality:{status:'supported',evidence:'manual',choices:['low'],requestField:'quality_level'},outputFormat:{status:'supported',evidence:'manual',choices:['png'],requestField:'format'},aspectRatio:{status:'supported',evidence:'manual',choices:['3:2'],requestField:'ratio'}}});
  const prompt='OWNED_EXACT_FIELDS',created=await registry.createImageTask(model.id,{studioModelId:model.id,prompt,size:'1536x1024',resolutionHint:'auto',aspectRatio:'3:2',aspectRatioHint:'auto',quality:'low',outputFormat:'png'},'workspace-exact'),task=await done(created.task.id),body=peer.requests.find(row=>row.body.prompt?.includes(prompt)).body;assert.equal(task.status,'completed');assert.equal(body.resolution,'1536x1024');assert.equal(body.ratio,'3:2');assert.equal(body.quality_level,'low');assert.equal(body.format,'png');assert.equal(body.size,undefined);assert.equal(body.quality,undefined);assert.equal(body.output_format,undefined);assert.match(body.prompt,/1536 x 1024 pixels/);assert.match(body.prompt,/aspect ratio: 3:2/);
  const hinted=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:'OWNED_EXACT_HINT_FIELDS',resolutionHint:'2016x1344',aspectRatioHint:'3:2'},'workspace-exact');assert.equal((await done(hinted.task.id)).status,'completed');const sent=peer.requests.find(row=>row.body.prompt?.includes('OWNED_EXACT_HINT_FIELDS')).body;assert.equal(sent.resolution,'2016x1344');assert.equal(sent.size,undefined);
});
test('Conflicting API/image hint aliases reject before POST or task persistence in either size policy',async()=>{
  const model=registry.modelDescriptors().find(model=>model.providerId==='own-exact-fields');await registry.recordModelCapabilities({providerId:model.providerId,modelId:model.model,capabilities:{size:{status:'supported',evidence:'manual',choices:['1536x1024']},aspectRatio:{status:'supported',evidence:'manual',choices:['1:1','3:2','16:9']}}});
  for(const imageSizePolicy of ['openai-size','prompt-only']){await registry.dispatch('save',{provider:{id:model.providerId,imageSizePolicy}});const before=peer.requests.length,count=asset.getOwnedSnapshot().tasks.length;
    for(const values of [{size:'1536x1024',resolutionHint:'2048x1152'},{aspectRatio:'1:1',aspectRatioHint:'16:9'},{size:'1536x1024',resolutionHint:'auto',aspectRatio:'16:9',aspectRatioHint:'auto'}])await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'Never submit contradictory parameters',...values},''),/conflict/);
    assert.equal(peer.requests.length,before);assert.equal(asset.getOwnedSnapshot().tasks.length,count);
  }
});
test('Image file formats and explicit response_format transport choices never cross their request-field semantics',async()=>{
  const provider={...configuration,id:'own-response-transport'};await registry.dispatch('save',{provider});await registry.dispatch('syncModels',{providerId:provider.id});const model=registry.modelDescriptors().find(model=>model.providerId===provider.id);
  await registry.recordModelCapabilities({providerId:provider.id,modelId:model.model,capabilities:{outputFormat:{status:'supported',evidence:'manual',choices:['png','url','b64_json'],requestField:'response_format'}}});const before=peer.requests.length;await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'Do not send a codec as response transport',outputFormat:'png'},''),/URL\/Base64 transport/);assert.equal(peer.requests.length,before);
  const created=await registry.createImageTask(model.id,{studioModelId:model.id,prompt:'OWNED_TRANSPORT_BASE64',outputFormat:'b64_json'},''),task=await done(created.task.id),body=peer.requests.find(row=>row.body.prompt==='OWNED_TRANSPORT_BASE64').body;assert.equal(task.status,'completed');assert.equal(body.response_format,'b64_json');assert.equal(body.output_format,undefined);assert.equal(task.artifacts[0].mime,'image/png');
  await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'Never submit contradictory response formats',outputFormat:'b64_json',responseFormat:'url'},''),/transport aliases conflict/);
  await registry.recordModelCapabilities({providerId:provider.id,modelId:model.model,capabilities:{outputFormat:{status:'supported',evidence:'manual',choices:['png','b64_json'],requestField:'output_format'}}});await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'Do not send transport as codec',outputFormat:'b64_json'},''),/image output format/i);await assert.rejects(()=>registry.createImageTask(model.id,{studioModelId:model.id,prompt:'Do not derive transport from codec choices',responseFormat:'b64_json'},''),/separately declared/);
});
test('Declared URL image transport preserves gateway inline image bytes as verified owned artifacts and rejects bad data URIs',async()=>{
  const calls=[],runtime=createAssetService({root:path.join(root,'inline-url-runtime'),pollIntervalMs:10,requestTimeoutMs:1000,fetch:async(url,init)=>{assert.equal(init.method,'POST');calls.push({url:String(url),body:JSON.parse(init.body)});return new Response(JSON.stringify({data:[{url:activeUri}]}));}});
  const local=createProviderRegistry({root:path.join(root,'inline-url-registry'),assetService:runtime,fetch:async(_url,init)=>{assert.equal(init.method,'GET');return new Response(JSON.stringify({data:[{id:'owned-inline-model'}]}));},seal,unseal});
  let activeUri='data:image/png;base64,'+peer.media.png.bytes.toString('base64');
  const wait=async id=>{for(let n=0;n<200;n++){const {task}=await runtime.dispatch('generator/getTask',{taskId:id});if(['completed','failed','interrupted'].includes(task.status))return task;await new Promise(resolve=>setTimeout(resolve,5));}throw Error('Owned inline image deadline');};
  try {
    await local.dispatch('save',{provider:{id:'own-inline-url',name:'Own URL transport',protocol:'openai-images',baseUrl:'http://127.0.0.1:9183',kinds:['image'],authMode:'none'}});await local.dispatch('syncModels',{providerId:'own-inline-url'});const model=local.modelDescriptors()[0];await local.recordModelCapabilities({providerId:model.providerId,modelId:model.model,capabilities:{outputFormat:{status:'supported',evidence:'manual',choices:['url','b64_json'],requestField:'response_format'}}});
    const create=()=>local.createImageTask(model.id,{studioModelId:model.id,prompt:'Owned URL output transport',outputFormat:'url'},'workspace-inline'),initial=await create(),task=await wait(initial.task.id);assert.equal(task.status,'completed');assert.equal(task.artifacts[0].sha256,peer.media.png.sha256);assert.equal(task.artifacts[0].width,48);assert.equal(task.artifacts[0].height,32);assert.equal(calls.length,1);assert.equal(calls[0].body.response_format,'url');assert.equal(calls[0].body.output_format,undefined);assert.equal(runtime.getArtifactPath(task.id,task.artifacts[0].id).sha256,peer.media.png.sha256);assert.equal(JSON.stringify(task).includes('data:image/'),false);
    for(const bad of ['data:text/html;base64,PGgxPm5vPC9oMT4=','data:image/png;base64,not-base64!','data:image/png;base64,AAAA','data:image/jpeg;base64,'+peer.media.png.bytes.toString('base64')]){activeUri=bad;const failed=await wait((await create()).task.id);assert.equal(failed.status,'failed');assert.equal(failed.artifacts.length,0);}
    assert.equal(calls.length,5,'Inline URL decoding never creates external GET or a second POST');
  }finally{await local.close();await runtime.close();}
});
