// Real local Git + Rust HTTP + shipped GUI, all in owned temp repositories.
// There are no remotes, providers, editor processes, accounts or user worktrees.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {randomUUID,createHash} from 'node:crypto';
const project=fileURLToPath(new URL('../../',import.meta.url));
const args=process.argv.slice(2);const option=(name,fallback)=>{const index=args.indexOf(name);return index<0?fallback:args[index+1];};
const run=path.resolve(option('--output',`F:/AI/AgentMake/temp/GameCowork/tests/git-e2e-${randomUUID()}`));
assert.ok(run.toLowerCase().startsWith(path.resolve('F:/AI/AgentMake/temp/GameCowork').toLowerCase()+path.sep));
const packaged=args.includes('--packaged');
const binary=path.resolve(option('--binary',path.join(project,packaged?'app/GameCowork.exe':'src/shell/target/debug/GameCowork.exe')));
const frontend=path.join(project,packaged?'app/frontend':'src/frontend/bundle');
const a=path.join(run,'Git A 中文'),b=path.join(run,'Git B'),unborn=path.join(run,'Unborn'),outside=path.join(run,'Outside'),forged=path.join(run,'Forged');
for(const dir of[a,b,unborn,outside,forged])fs.mkdirSync(dir,{recursive:true});
const checks=[],errors=[],blocked=[];let shell,context,page,gui,origin,log='',wa,wb;let lastScreenshot=0;
const git=(cwd,...commands)=>execFileSync('git',commands,{cwd,windowsHide:true,encoding:'utf8',env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:process.platform==='win32'?'NUL':'/dev/null'},stdio:['ignore','pipe','pipe']});
const sha=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function poll(fn,label,timeout=20000){const start=Date.now();while(!await fn()){assert.ok(Date.now()-start<timeout,`Timeout: ${label}`);await sleep(100);}}
async function request(endpoint,data){const response=await fetch(new URL(endpoint,origin),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(25000)});return{status:response.status,body:await response.json()};}
async function invoke(kind,data={},workspace=wa.workspaceKey){const id=randomUUID();const{status,body}=await request('/api/tauri/invoke',{messageType:kind,messageId:id,data,workspaceKey:workspace});assert.equal(status,200);assert.equal(body.messageId,id);assert.equal(body.data.done,true);return body.data;}
async function ok(kind,data={},workspace){const frame=await invoke(kind,data,workspace);assert.equal(frame.status,'success',`${kind}: ${frame.error}`);return frame.content;}
async function fail(kind,data,pattern,workspace){const frame=await invoke(kind,data,workspace);assert.equal(frame.status,'error',`${kind} must reject`);assert.match(frame.error,pattern);return frame;}
function initRepo(directory){git(directory,'init','--initial-branch=main');git(directory,'config','user.name','GameCowork Fixture');git(directory,'config','user.email','fixture@invalid');git(directory,'config','core.autocrlf','false');}
function baseline(directory){initRepo(directory);fs.writeFileSync(path.join(directory,'note 中文.txt'),'GCW_HEAD\n');fs.writeFileSync(path.join(directory,'delete.txt'),'GCW_DELETE_HEAD\n');fs.writeFileSync(path.join(directory,'rename old.txt'),'GCW_RENAME_HEAD\n');fs.writeFileSync(path.join(directory,'empty.txt'),'');fs.writeFileSync(path.join(directory,'binary.bin'),Buffer.from([0,1,255]));git(directory,'add','-A');git(directory,'commit','-m','owned fixture baseline');git(directory,'branch','feature');}
async function start(){shell=spawn(binary,[],{cwd:run,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...process.env,GAMECOWORK_APP_ROOT:run,GAMECOWORK_DATA_DIR:path.join(run,'data'),GAMECOWORK_FRONTEND_DIR:frontend,GAMECOWORK_CORE_DIR:path.join(project,'tests'),GAMECOWORK_CORE_ENTRY:path.join(project,'tests/fixtures/core-fixture.mjs'),GAMECOWORK_HEADLESS:'1',GAMECOWORK_TEST_MODE:'1',GAMECOWORK_FIXTURE_DATA_DIR:run,GAMECOWORK_FIXTURE_PROJECT_A:a,GAMECOWORK_FIXTURE_PROJECT_B:b,GAMECOWORK_FIXTURE_LOG:path.join(run,'core.jsonl')}});for(const stream of[shell.stdout,shell.stderr])stream.on('data',chunk=>{log+=chunk;const match=log.match(/HTTP: (http:\/\/127\.0\.0\.1:\d+\/)/);if(match)origin=match[1];});await poll(()=>origin,'Rust host');}
function playwrightModule(){const explicit=option('--playwright',process.env.GAMECOWORK_E2E_PLAYWRIGHT);if(explicit)return path.resolve(explicit);try{return createRequire(import.meta.url).resolve('playwright');}catch{}const cache=path.join(process.env.LOCALAPPDATA||os.tmpdir(),'npm-cache/_npx');const candidates=fs.readdirSync(cache).map(n=>path.join(cache,n,'node_modules/playwright/index.mjs')).filter(fs.existsSync).sort((a,b)=>fs.statSync(b).mtimeMs-fs.statSync(a).mtimeMs);assert.ok(candidates.length);return candidates[0];}
function chromiumBinary(){const explicit=option('--chrome',process.env.GAMECOWORK_E2E_CHROME);if(explicit)return path.resolve(explicit);const cache=path.join(process.env.LOCALAPPDATA||os.tmpdir(),'ms-playwright');for(const dir of fs.readdirSync(cache).filter(n=>/^chromium-\d+$/.test(n)).sort((a,b)=>+b.split('-')[1]-+a.split('-')[1]))for(const file of['chrome-win64/chrome.exe','chrome-win/chrome.exe'])if(fs.existsSync(path.join(cache,dir,file)))return path.join(cache,dir,file);}
async function snapshot(name){fs.writeFileSync(path.join(run,name+'.aria.txt'),await gui.locator('body').ariaSnapshot());await page.screenshot({path:path.join(run,name+'.png'),fullPage:true,animations:'disabled'});lastScreenshot++;}
async function browser(){const{chromium}=await import(pathToFileURL(playwrightModule()).href);context=await chromium.launchPersistentContext(path.join(run,'chromium'),{headless:true,executablePath:chromiumBinary(),viewport:{width:1440,height:960},locale:'zh-CN',colorScheme:'dark',serviceWorkers:'block'});await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname==='127.0.0.1'||['data:','blob:'].includes(url.protocol))return route.continue();blocked.push(url.origin);return route.abort('blockedbyclient');});await context.addInitScript(()=>{window.GAMECOWORK_SHELL=true;window.workspacePaths=[];window.vscMediaUrl='';});page=context.pages()[0]||await context.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto(origin,{waitUntil:'domcontentloaded'});await poll(()=>page.frames().some(f=>f.url().includes('/gui.html')),'GUI frame');gui=page.frames().find(f=>f.url().includes('/gui.html'));const next=gui.getByRole('button',{name:/^(下一步|Next|知道了|Got it)$/});await next.first().waitFor({state:'visible',timeout:3000}).catch(()=>{});for(let i=0;i<4&&await next.count()&&await next.first().isVisible();i++)await next.first().click();}
try{
 await start();baseline(a);baseline(b);initRepo(unborn);initRepo(outside);
 wa=(await request('/api/tauri/hub/open-workspace',{path:a})).body;wb=(await request('/api/tauri/hub/open-workspace',{path:b})).body;assert.ok(wa.workspaceKey&&wb.workspaceKey);await request('/api/tauri/hub/switch-workspace',{workspaceKey:wa.workspaceKey});
 fs.writeFileSync(path.join(a,'note 中文.txt'),'GCW_INDEX\n');git(a,'add','note 中文.txt');fs.writeFileSync(path.join(a,'note 中文.txt'),'GCW_WORKING\n');fs.unlinkSync(path.join(a,'delete.txt'));git(a,'mv','rename old.txt','rename new.txt');fs.writeFileSync(path.join(a,'-untracked [literal].txt'),'GCW_UNTRACKED\n');
 assert.equal(await ok('getBranch',{dir:a}),'main');assert.deepEqual(await ok('getGitBranches',{dir:a}),['feature','main']);checks.push('HTTP branch and local branch enumeration');
 const rows=await ok('getChangedFiles',{dir:a});const note=rows.find(r=>r.path==='note 中文.txt');assert.equal(note.staged,true);assert.equal(note.unstaged,true);assert.equal(rows.find(r=>r.path==='-untracked [literal].txt').untracked,true);assert.equal(rows.find(r=>r.path==='rename new.txt').oldPath,'rename old.txt');checks.push('NUL porcelain status: Unicode, combined staged/working, deletion, rename and untracked literal paths');
 assert.equal(await ok('getFileAtHead',{dir:a,filePath:'note 中文.txt'}),'GCW_HEAD\n');assert.equal(await ok('getFileAtIndex',{dir:a,filePath:'note 中文.txt'}),'GCW_INDEX\n');assert.equal(await ok('getFileAtHead',{dir:a,filePath:'empty.txt'}),'');assert.equal(await ok('getFileAtIndex',{dir:a,filePath:'missing.txt'}),'');await fail('getFileAtHead',{dir:a,filePath:'binary.bin'},/binary|UTF-8/);checks.push('Real HEAD/index bytes, empty/missing content, binary rejection');
 const staged=await ok('getDiff',{includeUnstaged:false});assert.ok(staged.join('\n').includes('GCW_INDEX'));assert.ok(!staged.join('\n').includes('GCW_WORKING'));const full=await ok('getDiff',{includeUnstaged:true});assert.ok(full.join('\n').includes('GCW_WORKING'));checks.push('Core getDiff returns staged/working patch arrays');
 let receipt=await ok('applyGitFileAction',{dir:a,action:'stage',paths:['note 中文.txt']});assert.equal(receipt.ok,true);assert.equal(await ok('getFileAtIndex',{dir:a,filePath:'note 中文.txt'}),'GCW_WORKING\n');receipt=await ok('applyGitFileAction',{dir:a,action:'unstage',paths:['note 中文.txt']});assert.equal(receipt.ok,true);assert.equal(await ok('getFileAtIndex',{dir:a,filePath:'note 中文.txt'}),'GCW_HEAD\n');assert.equal(fs.readFileSync(path.join(a,'note 中文.txt'),'utf8'),'GCW_WORKING\n');checks.push('Stage and unstage mutate the index and preserve working bytes');
 await ok('applyGitFileAction',{dir:a,action:'stage',paths:['note 中文.txt']});fs.writeFileSync(path.join(a,'note 中文.txt'),'GCW_DISCARD_DRAFT\n');receipt=await ok('applyGitFileAction',{dir:a,action:'discard',paths:['note 中文.txt']});assert.equal(fs.readFileSync(path.join(a,'note 中文.txt'),'utf8'),'GCW_WORKING\n');assert.equal(fs.readFileSync(path.join(receipt.backupPath,'files/note 中文.txt'),'utf8'),'GCW_DISCARD_DRAFT\n');receipt=await ok('applyGitFileAction',{dir:a,action:'discard',paths:['-untracked [literal].txt']});assert.equal(fs.existsSync(path.join(a,'-untracked [literal].txt')),false);assert.equal(fs.readFileSync(path.join(receipt.backupPath,'files/-untracked [literal].txt'),'utf8'),'GCW_UNTRACKED\n');checks.push('Confirmed discard restores index, removes only selected untracked file and preserves exact backup bytes');
 const before=sha(path.join(a,'.git/index'));for(const filePath of['../Outside/private.txt','.git/config',path.join(outside,'private.txt')])await fail('getFileAtHead',{dir:a,filePath},/path|metadata|traversal/i);await fail('getBranch',{dir:outside},/selected|workspace/);await fail('getBranch',{dir:b},/selected|workspace/);await fail('applyGitFileAction',{dir:a,action:'stage',paths:[':(glob)*']},/no longer changed|Invalid/);assert.equal(sha(path.join(a,'.git/index')),before);checks.push('Traversal, metadata, absolute path, magic pathspec and cross-workspace attacks reject without index mutation');
 const hookMarker=path.join(b,'HOOK_SHOULD_NOT_RUN');const hook=`#!/bin/sh\necho invoked > "${hookMarker.replaceAll('\\','/')}"\n`;fs.writeFileSync(path.join(b,'.git/hooks/post-checkout'),hook);fs.writeFileSync(path.join(b,'post-checkout'),hook);git(b,'add','post-checkout');git(b,'commit','-m','owned hook fixture');git(b,'branch','hooks-clean');
 await fail('switchGitBranch',{dir:a,branch:'feature'},/uncommitted|untracked/);assert.equal(git(a,'branch','--show-current').trim(),'main');await fail('switchGitBranch',{dir:a,branch:'--force'},/Invalid/);await fail('switchGitBranch',{dir:a,branch:'new-unrequested'},/existing local/);await ok('switchGitBranch',{dir:b,branch:'hooks-clean'},wb.workspaceKey);assert.equal(git(b,'branch','--show-current').trim(),'hooks-clean');assert.equal(git(a,'branch','--show-current').trim(),'main');assert.equal(fs.existsSync(hookMarker),false);fs.unlinkSync(path.join(b,'.git/hooks/post-checkout'));checks.push('Dirty and invalid branch switching reject; clean B switches without changing A or executing checkout hooks');
 const wu=(await request('/api/tauri/hub/open-workspace',{path:unborn})).body;fs.writeFileSync(path.join(unborn,'new.txt'),'GCW_UNBORN\n');await ok('applyGitFileAction',{dir:unborn,action:'stage',paths:['new.txt']},wu.workspaceKey);fs.writeFileSync(path.join(unborn,'new.txt'),'GCW_UNBORN_EDIT\n');await ok('applyGitFileAction',{dir:unborn,action:'unstage',paths:['new.txt']},wu.workspaceKey);assert.equal(fs.readFileSync(path.join(unborn,'new.txt'),'utf8'),'GCW_UNBORN_EDIT\n');assert.equal(await ok('getFileAtHead',{dir:unborn,filePath:'new.txt'},wu.workspaceKey),'');checks.push('Unborn repository stage/unstage preserves edited bytes without HEAD');
 fs.writeFileSync(path.join(a,'binary.bin'),Buffer.from([0,9,246]));receipt=await ok('applyGitFileAction',{dir:a,action:'discard',paths:['binary.bin']});assert.deepEqual(fs.readFileSync(path.join(a,'binary.bin')),Buffer.from([0,1,255]));assert.deepEqual(fs.readFileSync(path.join(receipt.backupPath,'files/binary.bin')),Buffer.from([0,9,246]));checks.push('Binary discard restores exact index bytes with recoverable SHA-protected backup');
 const crlf=path.join(run,'CRLF');fs.mkdirSync(crlf);initRepo(crlf);git(crlf,'config','core.autocrlf','true');fs.writeFileSync(path.join(crlf,'.gitattributes'),'*.txt text eol=crlf\n');fs.writeFileSync(path.join(crlf,'line.txt'),'GCW_CRLF\r\n');git(crlf,'add','-A');git(crlf,'commit','-m','owned CRLF fixture');const wc=(await request('/api/tauri/hub/open-workspace',{path:crlf})).body;fs.writeFileSync(path.join(crlf,'line.txt'),'GCW_CHANGED\n');await ok('applyGitFileAction',{dir:crlf,action:'discard',paths:['line.txt']},wc.workspaceKey);assert.equal(fs.readFileSync(path.join(crlf,'line.txt'),'utf8'),'GCW_CRLF\r\n');assert.equal(git(crlf,'status','--porcelain').trim(),'');checks.push('Discard uses real Git checkout eol conversion with repository core.autocrlf and .gitattributes; CRLF bytes/status are correct');
 fs.writeFileSync(path.join(crlf,'line.txt'),'GCW_FILTER_PROTECTED\r\n');git(crlf,'config','filter.fixture.clean','echo should-not-run');await fail('applyGitFileAction',{dir:crlf,action:'discard',paths:['line.txt']},/custom Git filters/,wc.workspaceKey);assert.equal(fs.readFileSync(path.join(crlf,'line.txt'),'utf8'),'GCW_FILTER_PROTECTED\r\n');checks.push('Custom Git filters reject mutation explicitly and preserve working bytes');
 fs.writeFileSync(path.join(forged,'.git'),'gitdir: '+path.join(b,'.git').replaceAll('\\','/')+'\n');const wf=(await request('/api/tauri/hub/open-workspace',{path:forged})).body;await fail('getChangedFiles',{dir:forged},/metadata|root|workspace/,wf.workspaceKey);checks.push('Forged external .git metadata cannot access another workspace');
 git(b,'switch','-c','conflict-side');fs.writeFileSync(path.join(b,'note 中文.txt'),'GCW_SIDE\n');git(b,'add','note 中文.txt');git(b,'commit','-m','owned conflict side');git(b,'switch','feature');fs.writeFileSync(path.join(b,'note 中文.txt'),'GCW_FEATURE\n');git(b,'add','note 中文.txt');git(b,'commit','-m','owned conflict feature');assert.throws(()=>git(b,'merge','conflict-side'));const conflictRows=await ok('getChangedFiles',{dir:b},wb.workspaceKey);assert.equal(conflictRows.find(r=>r.path==='note 中文.txt').conflicted,true);const conflictIndex=sha(path.join(b,'.git/index')),conflictBytes=sha(path.join(b,'note 中文.txt'));await fail('getFileAtIndex',{dir:b,filePath:'note 中文.txt'},/conflict/,wb.workspaceKey);for(const action of['stage','discard','unstage'])await fail('applyGitFileAction',{dir:b,action,paths:['note 中文.txt']},/conflict/,wb.workspaceKey);assert.equal(sha(path.join(b,'.git/index')),conflictIndex);assert.equal(sha(path.join(b,'note 中文.txt')),conflictBytes);checks.push('Unmerged files carry conflict state and refuse automatic index/discard actions without data loss');
 await request('/api/tauri/hub/switch-workspace',{workspaceKey:wa.workspaceKey});
 if(!args.includes('--skip-browser')){
  await browser();await gui.getByRole('button',{name:path.basename(a),exact:true}).first().waitFor({state:'visible'});await gui.getByRole('button',{name:path.basename(a),exact:true}).first().click();
  await gui.locator('[data-telemetry-id="toggle_right_sidebar"]').first().click();await gui.locator('[data-telemetry-id="right_sidebar_extension_menu"]').click();await snapshot('00-git-menu');await gui.getByText(/^(Git|Git 变更|版本控制)$/).last().click();await snapshot('01-git-list');
  await gui.locator('[data-telemetry-id="git_unstage_file"]').first().waitFor({state:'visible',timeout:20000});checks.push('Chromium original Git tab renders real branch and staged changes');
  const stagedSection=gui.getByText(/^(已暂存的更改|暂存的更改|Staged Changes)$/).first();await gui.getByText('note 中文.txt',{exact:true}).first().click();await poll(()=>gui.locator('.monaco-diff-editor').count(),'real Monaco diff');await snapshot('02-staged-diff');checks.push('Chromium staged file opens real Monaco HEAD/index diff');
  const actionResponse=page.waitForResponse(r=>r.url().includes('/api/tauri/invoke')&&r.request().postData()?.includes('applyGitFileAction'));await gui.locator('[data-telemetry-id="git_unstage_file"]').first().click();assert.equal((await(await actionResponse).json()).data.content.ok,true);await poll(async()=>!(await ok('getChangedFiles',{dir:a})).find(r=>r.path==='note 中文.txt')?.staged,'GUI unstage applied');await snapshot('03-unstaged');checks.push('Chromium unstage button changes actual repository state');
  // Open the branch menu and select feature while this repository is dirty.
  await gui.getByRole('button',{name:/^(切换分支|Switch Branch)$/}).first().click();await gui.locator('[data-telemetry-id="file_preview_select_branch"]').filter({hasText:'feature'}).first().click();await gui.getByText(/uncommitted or untracked changes/).first().waitFor({state:'visible'});assert.equal(git(a,'branch','--show-current').trim(),'main');await snapshot('04-dirty-switch-error');checks.push('Chromium rejected branch switch displays real reason and retains branch');
  await gui.getByRole('button',{name:/^(关闭|Close)$/}).last().click();
  await gui.getByRole('button',{name:'note 中文.txt',exact:true}).last().dblclick();
  const panel=gui.getByRole('complementary',{name:'File Preview Panel',exact:true});
  await panel.getByText('GCW_WORKING',{exact:false}).last().waitFor({state:'visible'});await panel.getByText('GCW_WORKING',{exact:false}).last().click();await page.keyboard.press('Control+a');await page.keyboard.type('GCW_UNSAVED_DRAFT');await poll(()=>panel.getByTestId('gamecowork-file-save').isEnabled(),'unsaved Git draft');
  const dirtyIndex=sha(path.join(a,'.git/index'));const noteRow=panel.getByRole('button',{name:'note 中文.txt',exact:true}).last().locator('..');
  await noteRow.hover();await noteRow.locator('[data-telemetry-id="git_stage_file"]').click();await gui.getByText(/Save or close the unsaved edits for this file/).first().waitFor({state:'visible'});assert.equal(sha(path.join(a,'.git/index')),dirtyIndex);assert.equal(fs.readFileSync(path.join(a,'note 中文.txt'),'utf8'),'GCW_WORKING\n');await snapshot('05-draft-stage-protected');await gui.getByRole('button',{name:/^(关闭|Close)$/}).last().click();
  await noteRow.hover();await noteRow.locator('[data-telemetry-id="git_discard_file"]').click();await gui.getByRole('button',{name:/^(放弃更改|Discard Changes)$/}).last().click();await gui.getByText(/Save or close the unsaved edits for this file/).first().waitFor({state:'visible'});assert.equal(fs.readFileSync(path.join(a,'note 中文.txt'),'utf8'),'GCW_WORKING\n');assert.ok(await panel.getByText('GCW_UNSAVED_DRAFT',{exact:false}).last().isVisible());await snapshot('06-draft-discard-protected');checks.push('Chromium unsaved source draft refuses stage and confirmed discard; disk, index and draft remain intact');
  assert.deepEqual(errors,[],'Browser has no uncaught page errors');
 }
 await request('/api/tauri/hub/close-workspace',{workspaceKey:wa.workspaceKey});await fail('getBranch',{dir:a},/open|workspace|Unknown/);checks.push('Closed workspace cannot execute Git requests');
}catch(error){errors.push(error.stack||String(error));throw error;}finally{
 await context?.close().catch(()=>{});if(shell?.exitCode===null){if(process.platform==='win32')execFileSync('taskkill.exe',['/PID',String(shell.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});else shell.kill('SIGTERM');}
 fs.writeFileSync(path.join(run,'shell.log'),log);fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({checks,errors,blocked,screenshots:lastScreenshot,success:errors.length===0},null,2));console.log(JSON.stringify({checks:checks.length,success:errors.length===0,report:path.join(run,'report.json')}));
}
