// Actual Rust host + shipped Monaco UI + frozen csharp-ls, with fixture Core.
// No model, Agent, provider, original LSP, user project, or automatic restore.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {randomUUID} from 'node:crypto';
import {createMonacoMenuProbe} from './monaco-menu-fixture.mjs';
const exec=promisify(execFile),project=fileURLToPath(new URL('../',import.meta.url)),args=process.argv.slice(2);
const option=(name,fallback)=>{const index=args.indexOf(name);return index<0?fallback:args[index+1];};
const base=path.resolve('F:/AI/AgentMake/temp/GameCowork'),run=path.resolve(option('--output',path.join(base,'tests','lsp-e2e-'+randomUUID())));assert.ok(run.toLowerCase().startsWith(base.toLowerCase()+path.sep));assert.equal(fs.existsSync(run),false);fs.mkdirSync(run,{recursive:true});
const packaged=args.includes('--packaged'),binary=path.resolve(option('--binary',path.join(project,packaged?'app/GameCowork.exe':'restored/shell/target/debug/GameCowork.exe'))),frontend=path.join(project,packaged?'app/frontend':'restored/frontend/dist-beautified'),lspDir=path.join(project,packaged?'app/lsp-csharp':'restored/lsp-csharp');
const a=path.join(run,'Workspace A 中文'),b=path.join(run,'Workspace B'),missing=path.join(run,'Missing Unity metadata'),data=path.join(run,'data');for(const dir of[a,b,missing,data])fs.mkdirSync(dir);
const checks=[],errors=[],blocked=[],rpc=[],pids=new Set();let shell,context,page,gui,origin,log='',wa,wb,menuProbe;
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));const same=(x,y)=>String(x||'').replaceAll('\\','/').toLowerCase()===String(y||'').replaceAll('\\','/').toLowerCase();
async function poll(fn,label,timeout=30000){const deadline=Date.now()+timeout;while(!await fn()){assert.ok(Date.now()<deadline,'Timeout: '+label);await sleep(100);}}
const source=type=>['namespace GameCoworkLspFixture;','public sealed class Calculator','{',`    public ${type} Combine(${type} left, ${type} right) => left + right;`,`    public ${type} First() => Combine(${type==='int'?'20':'"A"'}, ${type==='int'?'22':'"B"'});`,`    public ${type} Second() => Combine(${type==='int'?'20':'"A"'}, ${type==='int'?'22':'"B"'});`,'}',''].join('\n');
async function prepare(directory,type){fs.writeFileSync(path.join(directory,'global.json'),JSON.stringify({sdk:{version:'10.0.103',rollForward:'disable'}}));fs.writeFileSync(path.join(directory,'NuGet.Config'),'<configuration><packageSources><clear /></packageSources><auditSources><clear /></auditSources></configuration>');fs.writeFileSync(path.join(directory,'Fixture.csproj'),'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>disable</ImplicitUsings><Nullable>enable</Nullable><NuGetAudit>false</NuGetAudit></PropertyGroup></Project>');fs.writeFileSync(path.join(directory,'Calculator.cs'),source(type));for(const command of[['new','sln','--format','sln','--name','Fixture','--output',directory],['sln',path.join(directory,'Fixture.sln'),'add',path.join(directory,'Fixture.csproj')],['restore',path.join(directory,'Fixture.csproj'),'--configfile',path.join(directory,'NuGet.Config'),'--verbosity','quiet','-p:NuGetAudit=false']])await exec('dotnet',command,{cwd:directory,env:{...process.env,DOTNET_CLI_HOME:path.join(run,'dotnet-home'),DOTNET_CLI_TELEMETRY_OPTOUT:'1',DOTNET_SKIP_FIRST_TIME_EXPERIENCE:'1',NUGET_PACKAGES:path.join(run,'nuget')},windowsHide:true,timeout:60000});}
async function launch(){shell=spawn(binary,[],{cwd:run,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...process.env,GAMECOWORK_APP_ROOT:run,GAMECOWORK_DATA_DIR:data,GAMECOWORK_FRONTEND_DIR:frontend,GAMECOWORK_CORE_DIR:path.join(project,'tests'),GAMECOWORK_CORE_ENTRY:path.join(project,'tests/core-fixture.mjs'),GAMECOWORK_LSP_DIR:lspDir,GAMECOWORK_HEADLESS:'1',GAMECOWORK_TEST_MODE:'1',GAMECOWORK_FIXTURE_DATA_DIR:run,GAMECOWORK_FIXTURE_PROJECT_A:a,GAMECOWORK_FIXTURE_PROJECT_B:b,GAMECOWORK_FIXTURE_LOG:path.join(run,'core.jsonl')}});origin=null;for(const stream of[shell.stdout,shell.stderr])stream.on('data',chunk=>{log+=chunk;const match=chunk.toString().match(/HTTP: (http:\/\/127\.0\.0\.1:\d+\/)/);if(match)origin=match[1];});await poll(()=>origin,'Rust startup',60000);}
async function stop(){if(!shell)return;if(shell.exitCode===null&&shell.signalCode===null)await exec('taskkill.exe',['/PID',String(shell.pid),'/T','/F'],{windowsHide:true}).catch(()=>{});await poll(()=>shell.exitCode!==null||shell.signalCode!==null,'owned shell exit',10000);for(const pid of pids)await poll(()=>{try{process.kill(pid,0);return false;}catch{return true;}},'owned LSP PID '+pid+' reclaimed',10000);shell=null;}
async function http(endpoint,body){const response=await fetch(new URL(endpoint,origin),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(60000)});return{status:response.status,body:await response.json()};}
async function invoke(kind,payload={},workspace=wa.workspaceKey){const id=randomUUID(),response=await http('/api/tauri/invoke',{messageType:kind,messageId:id,data:payload,workspaceKey:workspace});assert.equal(response.status,200);assert.equal(response.body.messageId,id);return response.body.data;}
async function ok(kind,payload={},workspace){const frame=await invoke(kind,payload,workspace);assert.equal(frame.status,'success',kind+': '+frame.error);if(frame.content.pid)pids.add(frame.content.pid);return frame.content;}
async function fail(kind,payload,code,workspace){const frame=await invoke(kind,payload,workspace);assert.equal(frame.status,'error');if(code)assert.equal(frame.details?.code,code);return frame;}
async function status(workspace){return ok('lsp/status',{},workspace);}
async function enabled(workspace,value){const current=await status(workspace);return ok('lsp/setEnabled',{enabled:value,generation:current.generation},workspace);}
async function sync(workspace,text,version){const current=await status(workspace);return ok('lsp/syncDocument',{filePath:'Calculator.cs',text,version,generation:current.generation},workspace);}
async function query(workspace,method,text,version,needle='Combine',occurrence=1){let offset=-1;for(let index=0;index<=occurrence;index++){offset=text.indexOf(needle,offset+1);assert.ok(offset>=0);}const parts=text.slice(0,offset).split('\n'),current=await status(workspace);return ok(method,{filePath:'Calculator.cs',line:parts.length-1,character:parts.at(-1).length,version,requestId:randomUUID(),generation:current.generation,includeDeclaration:true},workspace);}
const hoverText=result=>result?.hover?.contents?.value||'';
function playwrightModule(){const explicit=option('--playwright',process.env.GAMECOWORK_E2E_PLAYWRIGHT);if(explicit)return path.resolve(explicit);try{return createRequire(import.meta.url).resolve('playwright');}catch{}const cache=path.join(process.env.LOCALAPPDATA||os.tmpdir(),'npm-cache/_npx');const matches=fs.readdirSync(cache).map(n=>path.join(cache,n,'node_modules/playwright/index.mjs')).filter(fs.existsSync).sort((x,y)=>fs.statSync(y).mtimeMs-fs.statSync(x).mtimeMs);assert.ok(matches.length);return matches[0];}
function chrome(){const cache=path.join(process.env.LOCALAPPDATA||os.tmpdir(),'ms-playwright');for(const dir of fs.readdirSync(cache).filter(n=>/^chromium-\d+$/.test(n)).sort((x,y)=>+y.split('-')[1]-+x.split('-')[1]))for(const file of['chrome-win64/chrome.exe','chrome-win/chrome.exe'])if(fs.existsSync(path.join(cache,dir,file)))return path.join(cache,dir,file);}
async function snapshot(name){fs.writeFileSync(path.join(run,name+'.aria.txt'),await gui.locator('body').ariaSnapshot());await page.screenshot({path:path.join(run,name+'.png'),fullPage:true,animations:'disabled'});}
async function browser(){const{chromium}=await import(pathToFileURL(playwrightModule()).href);context=await chromium.launchPersistentContext(path.join(run,'browser-'+randomUUID()),{headless:true,executablePath:chrome(),viewport:{width:1440,height:960},locale:'zh-CN',colorScheme:'dark',serviceWorkers:'block'});await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname==='127.0.0.1'||['data:','blob:'].includes(url.protocol))return route.continue();blocked.push(url.origin);return route.abort('blockedbyclient');});await context.addInitScript(()=>{window.GAMECOWORK_SHELL=true;window.workspacePaths=[];window.vscMediaUrl='';});page=context.pages()[0]||await context.newPage();page.on('pageerror',error=>errors.push(String(error)));page.on('console',message=>{if(message.text().startsWith('[LSP')||message.type()==='error')fs.appendFileSync(path.join(run,'browser-console.log'),message.text()+'\n');});page.on('response',async response=>{if(!response.url().includes('/api/tauri/invoke'))return;try{const request=response.request().postDataJSON(),kind=request.messageType;if(!kind?.startsWith('lsp/'))return;const result=await response.json();rpc.push({kind,workspaceKey:request.workspaceKey,generation:request.data?.generation,line:request.data?.line,character:request.data?.character,version:request.data?.version,status:result.data?.status,content:result.data?.content,error:result.data?.error});if(result.data?.content?.pid)pids.add(result.data.content.pid);}catch{}});await page.goto(origin,{waitUntil:'domcontentloaded'});await poll(()=>page.frames().some(frame=>frame.url().includes('/gui.html')),'GUI frame');gui=page.frames().find(frame=>frame.url().includes('/gui.html'));const next=gui.getByRole('button',{name:/^(下一步|Next|知道了|Got it)$/});await next.first().waitFor({state:'visible',timeout:3000}).catch(()=>{});for(let index=0;index<4&&await next.count()&&await next.first().isVisible();index++)await next.first().click();menuProbe=await createMonacoMenuProbe(context,page,gui);}
async function selectWorkspace(directory){await gui.getByRole('button',{name:path.basename(directory),exact:true}).first().click();await poll(async()=>gui.evaluate(async directory=>{const {s:store}=await import('/assets/store-c6kNGz30.js');const state=store.getState();return state.hub.workspaces.find(item=>item.workspaceKey===state.hub.activeWorkspaceKey)?.workspaceDir.replaceAll('\\','/').toLowerCase()===directory.replaceAll('\\','/').toLowerCase();},directory),'selected real workspace');}
async function openFile(){await gui.getByRole('complementary',{name:'File Preview Panel',exact:true}).getByRole('button',{name:'Calculator.cs',exact:true}).last().click();await gui.locator('.view-line').filter({hasText:'public sealed class Calculator'}).first().waitFor({state:'visible'});}
async function explorer(){const menu=gui.locator('[data-telemetry-id="right_sidebar_extension_menu"]');if(!await menu.isVisible())await gui.locator('[data-telemetry-id="toggle_right_sidebar"]').first().click();await menu.click();await gui.getByText(/^(文件浏览器|资源管理器|Explorer)$/).last().click();}
async function fullscreen(){const enter=gui.locator('[data-telemetry-id="enter_right_sidebar_fullscreen"]');if(await enter.isVisible())await enter.click();await gui.getByRole('button',{name:'退出全屏',exact:true}).waitFor({state:'visible'});}
async function cursorAtCall(text,needle='Combine'){const line=text.split('\n')[4],call=line.indexOf(needle);assert.ok(call>=0);await gui.locator('.view-line').filter({hasText:'public int First'}).first().click();await page.keyboard.press('End');for(let index=0;index<line.length-call;index++)await page.keyboard.press('ArrowLeft');}
async function hoverCall(text,needle){const line=gui.locator('.view-line').filter({hasText:'public int First'}).first(),word=line.getByText(needle,{exact:true});if(await word.count()){await word.first().hover();return;}const box=await line.boundingBox(),width=await line.evaluate(element=>{const style=getComputedStyle(element),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.font=[style.fontStyle,style.fontWeight,style.fontSize,style.fontFamily].join(' ');return ctx.measureText('M').width;});await page.mouse.move(box.x+width*(text.split('\n')[4].indexOf(needle)+2),box.y+box.height/2);}
let failure;
try{
 await Promise.all([prepare(a,'int'),prepare(b,'string')]);fs.writeFileSync(path.join(missing,'Calculator.cs'),source('int'));await launch();wa=(await http('/api/tauri/hub/open-workspace',{path:a})).body;wb=(await http('/api/tauri/hub/open-workspace',{path:b})).body;const wm=(await http('/api/tauri/hub/open-workspace',{path:missing})).body;await http('/api/tauri/hub/switch-workspace',{workspaceKey:wa.workspaceKey});
 const cold=await status(wa.workspaceKey);assert.equal(cold.enabled,false);assert.equal(cold.pid,null);await fail('lsp/syncDocument',{generation:cold.generation,filePath:'Calculator.cs',text:source('int'),version:1},'lsp_disabled');checks.push('HTTP cold registration/status does not start a server; disabled document sync rejects');
 await Promise.all([enabled(wa.workspaceKey,true),enabled(wb.workspaceKey,true)]);await sync(wa.workspaceKey,source('int'),1);await sync(wb.workspaceKey,source('string'),1);assert.ok(hoverText(await query(wa.workspaceKey,'lsp/hover',source('int'),1)).includes('int'));assert.ok(hoverText(await query(wb.workspaceKey,'lsp/hover',source('string'),1)).includes('string'));checks.push('HTTP explicit enable and real int/string semantic hover are isolated by workspace');
 const definition=await query(wa.workspaceKey,'lsp/goToDefinition',source('int'),1),references=await query(wa.workspaceKey,'lsp/findReferences',source('int'),1);assert.equal(definition.locations[0].range.start.line,3);assert.equal(references.locations.length,3);checks.push('HTTP normalized actual C# definition and references preserve source ranges');
 const edited=source('int').replaceAll('Combine','DraftMerge');await sync(wa.workspaceKey,edited,2);assert.ok(hoverText(await query(wa.workspaceKey,'lsp/hover',edited,2,'DraftMerge')).includes('DraftMerge'));assert.equal(fs.readFileSync(path.join(a,'Calculator.cs'),'utf8'),source('int'));const before=await status();await fail('lsp/syncDocument',{generation:before.generation,filePath:'Calculator.cs',text:source('int'),version:1},'lsp_document_version');await fail('lsp/hover',{generation:before.generation,filePath:'Calculator.cs',line:4,character:26,version:1,requestId:randomUUID()},'lsp_result_stale');await fail('lsp/syncDocument',{generation:before.generation,filePath:path.join(b,'Calculator.cs'),text:source('string'),version:3},'lsp_path_denied');checks.push('HTTP unsaved text changes semantics without disk writes; stale versions and cross-workspace paths reject');
 for(const escaped of ['\\\\127.0.0.1\\unrequested-share\\a.cs','file:///%5C%5C127.0.0.1%5Cunrequested-share%5Ca.cs','\\unrequested-root\\a.cs'])await fail('lsp/syncDocument',{generation:before.generation,filePath:escaped,text:edited,version:3},'lsp_path_denied');checks.push('UNC, encoded UNC, device/rooted paths reject before filesystem canonicalization or network probing');
 await sync(wa.workspaceKey,edited,3);const oldClose=await ok('lsp/closeDocument',{generation:before.generation,filePath:'Calculator.cs',version:2});assert.equal(oldClose.closed,false);assert.ok(hoverText(await query(wa.workspaceKey,'lsp/hover',edited,3,'DraftMerge')).includes('DraftMerge'));checks.push('An older delayed close cannot remove a newer document owner or its real language semantics');
 const missingStatus=await status(wm.workspaceKey);assert.equal(missingStatus.supported,false);await fail('lsp/setEnabled',{enabled:true,generation:missingStatus.generation},'lsp_project_missing',wm.workspaceKey);assert.equal((await status(wm.workspaceKey)).pid,null);checks.push('Unity metadata missing is explicit unsupported and cannot silently create project files');
 const homeBefore=await status('default');await fail('lsp/setEnabled',{enabled:true,generation:homeBefore.generation},'lsp_project_missing','default');const homeFailed=await status('default');assert.equal(homeFailed.enabled,false);assert.notEqual(homeFailed.generation,homeBefore.generation);const home=path.join(data,'Workspace');await prepare(home,'int');await enabled('default',true);await sync('default',source('int'),1);assert.ok(hoverText(await query('default','lsp/hover',source('int'),1)).includes('int'));await enabled('default',false);checks.push('Default home workspace recovers from missing metadata, refreshes its handle and successfully enables after explicit SDK preparation');
 await enabled(wa.workspaceKey,false);const stale=before.generation;await fail('lsp/closeDocument',{generation:stale,filePath:'Calculator.cs'},'lsp_workspace_closed');assert.ok(hoverText(await query(wb.workspaceKey,'lsp/hover',source('string'),1)).includes('string'));checks.push('HTTP disable invalidates old generation while B still serves real requests');
 const preferences=path.join(data,'lsp-preferences.json');await exec('attrib.exe',['+R',preferences],{windowsHide:true});const denied=await status();await fail('lsp/setEnabled',{generation:denied.generation,enabled:true},'lsp_preferences_failed');const afterDenied=await status();assert.equal(afterDenied.enabled,false);assert.equal(afterDenied.pid,null);const beforeDisable=await status(wb.workspaceKey);await fail('lsp/setEnabled',{generation:beforeDisable.generation,enabled:false},'lsp_preferences_failed',wb.workspaceKey);assert.equal((await status(wb.workspaceKey)).enabled,false);assert.equal((await status(wb.workspaceKey)).pid,null);await exec('attrib.exe',['-R',preferences],{windowsHide:true});await enabled(wb.workspaceKey,true);await sync(wb.workspaceKey,source('string'),1);checks.push('Preference write failures leave no ghost enabled server and disable remains honestly stopped; writable recovery succeeds');
 if(!args.includes('--skip-browser')){
  await browser();await selectWorkspace(a);await gui.locator('[data-telemetry-id="toggle_right_sidebar"]').first().click();await gui.locator('[data-telemetry-id="right_sidebar_extension_menu"]').click();await gui.getByText(/^(文件浏览器|资源管理器|Explorer)$/).last().click();await openFile();await snapshot('01-disabled-csharp');const chip=gui.getByTestId('gamecowork-lsp-status');assert.equal(await chip.getAttribute('data-lsp-connected'),'false');await chip.click();await poll(async()=>await chip.getAttribute('data-lsp-connected')==='true','actual C# connected badge',60000);await snapshot('02-connected-csharp');checks.push('Chromium original C# button starts the real server and shows connected only after ready');
  await fullscreen();await hoverCall(source('int'),'Combine');await gui.locator('.monaco-hover').filter({hasText:'int Calculator.Combine'}).first().waitFor({state:'visible',timeout:15000});await snapshot('03-real-hover');checks.push('Chromium Monaco hover renders the real C# method signature');
  await cursorAtCall(source('int'));await gui.locator('.view-line').filter({hasText:'public int First'}).first().getByText('Combine',{exact:true}).click({button:'right'});await snapshot('04-definition-menu');const menuReady=await menuProbe.waitForReady('转到 C# 定义');fs.writeFileSync(path.join(run,'menu-ready.json'),JSON.stringify(menuReady,null,2));await gui.getByText('转到 C# 定义',{exact:true}).click();await poll(async()=>await gui.locator('.monaco-editor .active-line-number').first().textContent()==='4','actual declaration navigation');await snapshot('04-real-definition');checks.push('Chromium context action invokes the original definition provider and navigates to the real declaration line');
  await gui.getByRole('menu').waitFor({state:'hidden'});await gui.locator('.view-line').filter({hasText:'public int Combine'}).first().getByText('Combine',{exact:true}).click();await gui.getByTestId('gamecowork-csharp-references').click();await snapshot('05-after-references');await gui.getByTestId('gamecowork-lsp-references').getByText('引用 (3)',{exact:true}).waitFor({state:'visible',timeout:15000});await snapshot('05-real-references');checks.push('Chromium reference list uses the original provider and actual declaration/call locations');await gui.getByRole('button',{name:'关闭 C# 引用',exact:true}).click();
  await gui.locator('.view-line').filter({hasText:'public int First'}).first().getByText('Combine',{exact:true}).click();const keyboardStart=rpc.length;assert.equal(await gui.evaluate(()=>window.GAMECOWORK_SHELL),true);assert.equal(await page.evaluate(()=>window.GAMECOWORK_SHELL),true);await page.keyboard.press('F12');await poll(()=>rpc.slice(keyboardStart).some(item=>item.kind==='lsp/goToDefinition'&&item.status==='success'),'full-wrapper F12 actual provider RPC');await poll(async()=>await gui.locator('.monaco-editor .active-line-number').first().textContent()==='4','full-wrapper F12 declaration navigation');await gui.locator('.view-line').filter({hasText:'public int Combine'}).first().getByText('Combine',{exact:true}).click();await page.keyboard.press('Shift+F12');await gui.getByTestId('gamecowork-lsp-references').getByText('引用 (3)',{exact:true}).waitFor({state:'visible',timeout:15000});await snapshot('05-keyboard-definition-references');await gui.getByRole('button',{name:'关闭 C# 引用',exact:true}).click();checks.push('Full desktop wrapper with native Shell initialization allows F12 and Shift+F12 to reach real Monaco definition/reference providers');
  await gui.locator('.view-line').filter({hasText:'public sealed class Calculator'}).first().click();await page.keyboard.press('Control+a');await page.keyboard.insertText(edited);await poll(()=>gui.getByTestId('gamecowork-file-save').isEnabled(),'unsaved C# draft');await poll(()=>rpc.some(item=>item.kind==='lsp/syncDocument'&&item.status==='success'&&item.version>=2),'native unsaved sync');await hoverCall(edited,'DraftMerge');await gui.locator('.monaco-hover').filter({hasText:'int Calculator.DraftMerge'}).first().waitFor({state:'visible',timeout:15000});assert.equal(fs.readFileSync(path.join(a,'Calculator.cs'),'utf8'),source('int'));await snapshot('06-unsaved-semantic-hover');checks.push('Chromium unsaved edits drive real semantic hover while original source bytes remain intact');
  await selectWorkspace(b);await explorer();await openFile();await poll(async()=>await gui.getByTestId('gamecowork-lsp-status').getAttribute('data-lsp-connected')==='true','B persisted enabled and semantic connection');await poll(()=>rpc.some(item=>item.kind==='lsp/syncDocument'&&item.workspaceKey===wb.workspaceKey&&item.status==='success'),'B actual captured Monaco sync');await fullscreen();const bWord=gui.locator('.view-line').filter({hasText:'public string First'}).first().getByText('Combine',{exact:true});await bWord.hover();await gui.locator('.monaco-hover').filter({hasText:'string Calculator.Combine'}).first().waitFor({state:'visible',timeout:15000});await snapshot('07-workspace-b');checks.push('Chromium switches to B with captured route and actual string semantic hover, preserving independent language identity');
  await menuProbe?.dispose();menuProbe=null;await context.close();context=null;
 }
 await enabled(wa.workspaceKey,true);await stop();await launch();const restarted=await status(wa.workspaceKey);assert.equal(restarted.enabled,true);assert.equal(restarted.pid,null);assert.equal(restarted.connected,false);
 if(!args.includes('--skip-browser')){await browser();await selectWorkspace(a);await explorer();await openFile();await poll(async()=>await gui.getByTestId('gamecowork-lsp-status').getAttribute('data-lsp-connected')==='true','cold GUI reconnects enabled C#',60000);await fullscreen();await hoverCall(source('int'),'Combine');await gui.locator('.monaco-hover').filter({hasText:'int Calculator.Combine'}).first().waitFor({state:'visible',timeout:15000});await snapshot('08-cold-gui-reconnected');await menuProbe?.dispose();menuProbe=null;await context.close();context=null;checks.push('Cold Chromium GUI restores its own enabled preference and reconnects real semantic hover without any model');}
 else {await sync(wa.workspaceKey,source('int'),1);assert.ok(hoverText(await query(wa.workspaceKey,'lsp/hover',source('int'),1)).includes('int'));}
 checks.push('Cold host restart restores enabled preference without automatic process startup; fresh document query reconnects');
 await http('/api/tauri/hub/close-workspace',{workspaceKey:wa.workspaceKey});const closed=await invoke('lsp/status',{},wa.workspaceKey);assert.equal(closed.status,'error');checks.push('Closing the actual host workspace reclaims its language service and rejects captured requests');
 assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
}catch(error){failure=error;errors.push(error.stack||String(error));process.exitCode=1;if(gui&&context)await snapshot('failure').catch(()=>{});}finally{
 await menuProbe?.dispose();await context?.close().catch(()=>{});await stop().catch(error=>errors.push(String(error)));fs.writeFileSync(path.join(run,'shell.log'),log);fs.writeFileSync(path.join(run,'rpc.json'),JSON.stringify(rpc,null,2));fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({success:!failure&&errors.length===0,packaged,fixtureCore:true,modelRequests:0,checks,errors,blocked,run},null,2));console.log(JSON.stringify({success:!failure&&errors.length===0,checks:checks.length,report:path.join(run,'report.json'),error:failure?.message}));
}
