 ✓ [// @bun
import{spawnSync as u}from"child_process";import{closeSync as i,promises as v,openSync as n}from"fs";import R from"os";import K from"path";import p from"readline";import m from"tty";import{parseArgs as a}from"util";var M=Boolean(process.stdout.isTTY&&!("NO_COLOR"in process.env)),O=M?"\x1B[0m":"",T=M?"\x1B[1m":"",I=M?"\x1B[2m":"",r=M?"\x1B[31m":"",t=M?"\x1B[32m":"",B=M?"\x1B[36m":"",e=M?"\x1B[90m":"",w={question:`${B}?${O}`,check:`${t}\u2714${O}`,cross:`${r}\u2716${O}`},y=`${e}> ${O}`,qq=`
${M?T:""}THANK YOU! ${O}`;function Jq(){if(process.stdin.isTTY&&process.stdout.isTTY)return{input:process.stdin,output:process.stdout,cleanup:()=>{}};let N=["CON"];for(let J of N)try{let q=n(J,"r+"),Q=new m.ReadStream(q),Y=new m.WriteStream(q);return Q.setEncoding("utf8"),{input:Q,output:Y,cleanup:()=>{Q.destroy(),Y.destroy();try{i(q)}catch{}}}}catch{}return null}var x=(N)=>{process.stderr.write(`${w.cross} ${N}
`)},C=(N)=>{if(!N)return!1;let J=N.trim();if(!J.includes("@"))return!1;if(!J.includes("."))return!1;return!0};function Nq(N){try{let{values:J,positionals:q}=a({args:N,allowPositionals:!0,strict:!1,options:{email:{type:"string",short:"e"},help:{type:"boolean",short:"h"}}});return{email:J.email,help:Boolean(J.help),positionals:q}}catch(J){let q=J instanceof Error?J.message:String(J);return x(q),process.exit(1),{email:void 0,help:!1,positionals:[]}}}function Qq(){let N=`${T}${B}bun feedback${O}`,J=`${T}Usage${O}
  bun feedback [options] [feedback text ... | files ...]`,q=`${T}Options${O}
  ${B}-e${O}, ${B}--email${O} <email>   Set the email address used for this submission
  ${B}-h${O}, ${B}--help${O}            Show this help message and exit`,Q=`${T}Examples${O}
  bun feedback "Love the new release!"
  bun feedback report.txt details.log
  echo "please document X" | bun feedback --email you@example.com`;console.log([N,"",J,"",q,"",Q].join(`
`))}async function Uq(){let N=process.env.BUN_INSTALL??K.join(R.homedir(),".bun"),J=K.join(N,"feedback");try{let Q=(await v.readFile(J,"utf8")).trim();return Q.length>0?Q:void 0}catch(q){if(q.code!=="ENOENT")console.warn(`Unable to read ${J}:`,q.message);return}}async function Wq(N){let J=process.env.BUN_INSTALL;if(!J)return;let q=K.join(J,"feedback");try{await v.mkdir(K.dirname(q),{recursive:!0}),await v.writeFile(q,`${N.trim()}
`,"utf8")}catch(Q){console.warn(`Unable to persist email to ${q}:`,Q.message)}}function Xq(){let N=u("git",["config","user.email"],{encoding:"utf8",stdio:["ignore","pipe","ignore"]});if(N.status!==0)return;let J=N.stdout.trim();return J.length>0?J:void 0}async function Zq(N,J){if(!N)return J&&C(J)?J:void 0;let q=J;for(;;){let Q=await $q(N,q);if(typeof Q==="string"&&C(Q))return Q.trim();N.output.write(`${w.cross} Please provide a valid email address containing "@" and ".".
`),q=void 0}}async function $q(N,J){let{input:q,output:Q}=N;p.emitKeypressEvents(q);let Y=typeof q.isRaw==="boolean"?q.isRaw:void 0;if(typeof q.setRawMode==="function")q.setRawMode(!0);if(typeof q.resume==="function")q.resume();let Z=J??"",W=Z.length>0,U="",V=!1,G=()=>{if(Q.write(`\r\x1B[2K${w.question} ${T}Email${O}: `),W&&Z.length>0)Q.write(`${I}<${Z}>${O}`),Q.write(`\x1B[${Z.length+2}D`);else Q.write(U)};return G(),await new Promise((L)=>{let z=(X)=>{if(V)return;if(V=!0,q.removeListener("keypress",j),typeof q.setRawMode==="function")if(typeof Y==="boolean")q.setRawMode(Y);else q.setRawMode(!1);if(typeof q.pause==="function")q.pause();Q.write(`
`),L(X)},j=(X,$)=>{if(!$&&X){if(W)W=!1,U="",G();U+=X,Q.write(X);return}if($&&($.sequence==="\x03"||$.ctrl&&$.name==="c")){z(),process.exit(130);return}if($?.name==="return"){if(W&&Z.length>0){z(Z);return}let P=U.trim();z(P.length>0?P:void 0);return}if($?.name==="backspace"){if(W)return;if(U.length>0)U=U.slice(0,-1),G();return}if(!X)return;if($&&$.name&&$.name.length>1&&$.name!=="space")return;if(W)W=!1,U="",G();U+=X,Q.write(X)};q.on("keypress",j)})}async function Hq(N,J){if(!N)return;let{input:q,output:Q}=N;p.emitKeypressEvents(q);let Y=typeof q.isRaw==="boolean"?q.isRaw:void 0;if(typeof q.setRawMode==="function")q.setRawMode(!0);if(typeof q.resume==="function")q.resume();let Z=`${w.question} ${T}Share your feedback with Bun's team${O} ${I}(Enter to send, Shift+Enter for a newline)${O}`;if(Q.write(`${Z}
`),J.length>0)Q.write(`${I}+ ${J.map((G)=>G.filename).join(", ")}${O}
`);Q.write(`${y}`);let W=[""],U=0,V=!1;return await new Promise((G)=>{let L=(j)=>{if(V)return;if(V=!0,q.removeListener("keypress",z),typeof q.setRawMode==="function")if(typeof Y==="boolean")q.setRawMode(Y);else q.setRawMode(!1);if(typeof q.pause==="function")q.pause();Q.write(`
`),G(j)},z=(j,X)=>{if(!X){if(j)W[U]+=j,Q.write(j);return}if(X.sequence==="\x03"||X.ctrl&&X.name==="c"){L(),process.exit(130);return}if(X.name==="return"){if(X.shift){W.push(""),U+=1,Q.write(`
${y}`);return}let $=W.join(`
`);L($);return}if(X.name==="backspace"){let $=W[U];if($.length>0)W[U]=$.slice(0,-1),Q.write("\b \b");else if(U>0)W.pop(),U-=1,Q.write("\r\x1B[2K"),Q.write("\x1B[F"),Q.write("\r\x1B[2K"),Q.write(`${y}${W[U]}`);return}if(X.name&&X.name.length>1&&X.name!=="space")return;if(j)W[U]+=j,Q.write(j)};q.on("keypress",z)})}async function Oq(){let N=process.stdin;if(!N||N.isTTY)return;if(typeof N.setEncoding==="function")N.setEncoding("utf8");if(typeof N.resume==="function")N.resume();let J=[];for await(let Q of N)J.push(typeof Q==="string"?Q:Q.toString("utf8"));let q=J.join("");return q.length>0?q:void 0}async function Yq(N){let J=new Set;if(J.add(N),N.startsWith("~/"))J.add(K.join(R.homedir(),N.slice(2)));let q=K.join(process.cwd(),N);J.add(q);for(let Q of J)try{if((await v.stat(Q)).isFile())return Q}catch(Y){let Z=Y.code;if(Z&&(Z==="ENOENT"||Z==="ENOTDIR"))continue;console.warn(`Unable to inspect ${Q}:`,Y.message)}return}async function _q(N){let J=[],q=[],Q=[],Y=()=>{if(Q.length>0)J.push(Q.join(" ")),Q=[]};for(let Z of N){let W=await Yq(Z);if(W)try{let U=await Bun.file(W).bytes();if(U.length>10485760)U=U.slice(0,10485760);Y(),q.push({filename:K.normalize(K.relative(process.cwd(),W)),content:U});continue}catch{}Q.push(Z)}return Y(),{messageParts:J,files:q}}function E(N,J){if(N.family==="IPv4")switch(J){case"none":return"ipv4";case"ipv4":return"ipv4_and_ipv6";case"ipv6":return"ipv4_and_ipv6";case"ipv4_and_ipv6":return"ipv4_and_ipv6"}else if(N.family==="IPv6")switch(J){case"none":return"ipv6";case"ipv4":return"ipv4_and_ipv6";case"ipv6":return"ipv4_and_ipv6";case"ipv4_and_ipv6":return"ipv4_and_ipv6"}return J}function jq(){let N=u("git",["rev-list","--max-parents=0","HEAD"],{encoding:"utf8",stdio:["ignore","pipe","ignore"]});if(N.status!==0)return;return N.stdout.split(/\r?\n/).find((q)=>q.trim().length>0)?.trim()}async function Gq(){let N=process.argv.slice(1),J=null;try{let{email:q,help:Q,positionals:Y}=Nq(N);if(Q){Qq();return}J=Jq();let Z=(_)=>{J?.cleanup(),process.exit(_)};if(q&&!C(q))x("The provided email must include both '@' and '.'."),Z(1);let W=await Uq(),U=C(W)?W.trim():void 0,V=Xq(),G=C(V)?V.trim():void 0,L=J!==null,z=q?.trim()??U??G;if(L&&!q&&!U)z=await Zq(J,z??G??void 0);if(!C(z)){if(!L)x("Unable to determine email automatically. Pass --email <address>.");else x("An email address is required. Pass --email or configure git user.email.");Z(1);return}let j=z.trim();if(process.env.BUN_INSTALL&&!U)await Wq(j);let X=await Oq(),$=await _q(Y),P=$.messageParts,b=[];if(X&&X.trim().length>0)b.push(X);for(let _ of P)if(_.trim().length>0)b.push(_);let h=b.length>0?b.join(b.length>1?`

`:""):"";if(h.trim().length===0&&J){let _=await Hq(J,$.files);if(_&&_.trim().length>0)h=_}let k=h.trim();if(k.length===0){x("No feedback provided. Supply text, file paths, or pipe input."),Z(1);return}let s=k,c=jq(),l=process.env.BUN_FEEDBACK_URL||"https://bun.report/v1/feedback",H=new FormData;H.append("email",j),H.append("message",s);for(let _ of $.files)H.append("files[]",new Blob([_.content]),_.filename);let g=Bun.randomUUIDv7();if(H.append("platform","win32"),H.append("arch","x64"),H.append("bunRevision",Bun.revision),H.append("hardwareConcurrency",String(navigator.hardwareConcurrency)),H.append("bunVersion",Bun.version),H.append("bunBuild",K.basename(process.release.sourceUrl,K.extname(process.release.sourceUrl))),H.append("availableMemory",String(process.availableMemory())),H.append("totalMemory",String(R.totalmem())),H.append("osVersion",String(R.version())),H.append("osRelease",String(R.release())),H.append("id",g),!1)H.append("docker","true");let S="none",F="none";try{let _=Object.entries(R.networkInterfaces()||{});for(let[o,d]of _)for(let D of d||[])if(D.family==="IPv4")if(D.internal)F=E(D,F);else S=E(D,S);else if(D.family==="IPv6")if(D.internal)F=E(D,F);else S=E(D,S)}catch{}if(H.append("localIPSupport",F),H.append("remoteIPSupport",S),c)H.append("projectId",c);let A=await fetch(l,{method:"POST",body:H});if(!A.ok||A.status!==200){let _=await A.text().catch(()=>"");if(x(`Failed to send feedback (${A.status} ${A.statusText}).`),_)process.stderr.write(`${_}
`);Z(1)}let f="";if(M)f=`
${I}ID: ${g}${O}`;else f=`
ID: ${g}`;process.stdout.write(`${w.check} Feedback sent.
${f}${qq}
`)}finally{J?.cleanup()}}await Gq().catch((N)=>{let J=N instanceof Error?N.message:String(N);x(`Unexpected error while sending feedback: ${J}`),process.exit(1)});
